// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "dense_array_ap_fixed_4u_array_ap_fixed_28_16_1_0_0_16u_config15_s.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic dense_array_ap_fixed_4u_array_ap_fixed_28_16_1_0_0_16u_config15_s::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic dense_array_ap_fixed_4u_array_ap_fixed_28_16_1_0_0_16u_config15_s::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<16> dense_array_ap_fixed_4u_array_ap_fixed_28_16_1_0_0_16u_config15_s::ap_ST_fsm_state1 = "1";
const sc_lv<16> dense_array_ap_fixed_4u_array_ap_fixed_28_16_1_0_0_16u_config15_s::ap_ST_fsm_pp0_stage0 = "10";
const sc_lv<16> dense_array_ap_fixed_4u_array_ap_fixed_28_16_1_0_0_16u_config15_s::ap_ST_fsm_state4 = "100";
const sc_lv<16> dense_array_ap_fixed_4u_array_ap_fixed_28_16_1_0_0_16u_config15_s::ap_ST_fsm_state5 = "1000";
const sc_lv<16> dense_array_ap_fixed_4u_array_ap_fixed_28_16_1_0_0_16u_config15_s::ap_ST_fsm_state6 = "10000";
const sc_lv<16> dense_array_ap_fixed_4u_array_ap_fixed_28_16_1_0_0_16u_config15_s::ap_ST_fsm_state7 = "100000";
const sc_lv<16> dense_array_ap_fixed_4u_array_ap_fixed_28_16_1_0_0_16u_config15_s::ap_ST_fsm_state8 = "1000000";
const sc_lv<16> dense_array_ap_fixed_4u_array_ap_fixed_28_16_1_0_0_16u_config15_s::ap_ST_fsm_state9 = "10000000";
const sc_lv<16> dense_array_ap_fixed_4u_array_ap_fixed_28_16_1_0_0_16u_config15_s::ap_ST_fsm_state10 = "100000000";
const sc_lv<16> dense_array_ap_fixed_4u_array_ap_fixed_28_16_1_0_0_16u_config15_s::ap_ST_fsm_state11 = "1000000000";
const sc_lv<16> dense_array_ap_fixed_4u_array_ap_fixed_28_16_1_0_0_16u_config15_s::ap_ST_fsm_state12 = "10000000000";
const sc_lv<16> dense_array_ap_fixed_4u_array_ap_fixed_28_16_1_0_0_16u_config15_s::ap_ST_fsm_state13 = "100000000000";
const sc_lv<16> dense_array_ap_fixed_4u_array_ap_fixed_28_16_1_0_0_16u_config15_s::ap_ST_fsm_state14 = "1000000000000";
const sc_lv<16> dense_array_ap_fixed_4u_array_ap_fixed_28_16_1_0_0_16u_config15_s::ap_ST_fsm_state15 = "10000000000000";
const sc_lv<16> dense_array_ap_fixed_4u_array_ap_fixed_28_16_1_0_0_16u_config15_s::ap_ST_fsm_state16 = "100000000000000";
const sc_lv<16> dense_array_ap_fixed_4u_array_ap_fixed_28_16_1_0_0_16u_config15_s::ap_ST_fsm_state17 = "1000000000000000";
const bool dense_array_ap_fixed_4u_array_ap_fixed_28_16_1_0_0_16u_config15_s::ap_const_boolean_1 = true;
const sc_lv<32> dense_array_ap_fixed_4u_array_ap_fixed_28_16_1_0_0_16u_config15_s::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> dense_array_ap_fixed_4u_array_ap_fixed_28_16_1_0_0_16u_config15_s::ap_const_lv32_1 = "1";
const bool dense_array_ap_fixed_4u_array_ap_fixed_28_16_1_0_0_16u_config15_s::ap_const_boolean_0 = false;
const sc_lv<32> dense_array_ap_fixed_4u_array_ap_fixed_28_16_1_0_0_16u_config15_s::ap_const_lv32_F = "1111";
const sc_lv<1> dense_array_ap_fixed_4u_array_ap_fixed_28_16_1_0_0_16u_config15_s::ap_const_lv1_0 = "0";
const sc_lv<32> dense_array_ap_fixed_4u_array_ap_fixed_28_16_1_0_0_16u_config15_s::ap_const_lv32_2 = "10";
const sc_lv<32> dense_array_ap_fixed_4u_array_ap_fixed_28_16_1_0_0_16u_config15_s::ap_const_lv32_E = "1110";
const sc_lv<1> dense_array_ap_fixed_4u_array_ap_fixed_28_16_1_0_0_16u_config15_s::ap_const_lv1_1 = "1";
const sc_lv<5> dense_array_ap_fixed_4u_array_ap_fixed_28_16_1_0_0_16u_config15_s::ap_const_lv5_0 = "00000";
const sc_lv<4> dense_array_ap_fixed_4u_array_ap_fixed_28_16_1_0_0_16u_config15_s::ap_const_lv4_0 = "0000";
const sc_lv<4> dense_array_ap_fixed_4u_array_ap_fixed_28_16_1_0_0_16u_config15_s::ap_const_lv4_1 = "1";
const sc_lv<4> dense_array_ap_fixed_4u_array_ap_fixed_28_16_1_0_0_16u_config15_s::ap_const_lv4_2 = "10";
const sc_lv<4> dense_array_ap_fixed_4u_array_ap_fixed_28_16_1_0_0_16u_config15_s::ap_const_lv4_3 = "11";
const sc_lv<4> dense_array_ap_fixed_4u_array_ap_fixed_28_16_1_0_0_16u_config15_s::ap_const_lv4_4 = "100";
const sc_lv<4> dense_array_ap_fixed_4u_array_ap_fixed_28_16_1_0_0_16u_config15_s::ap_const_lv4_5 = "101";
const sc_lv<4> dense_array_ap_fixed_4u_array_ap_fixed_28_16_1_0_0_16u_config15_s::ap_const_lv4_6 = "110";
const sc_lv<4> dense_array_ap_fixed_4u_array_ap_fixed_28_16_1_0_0_16u_config15_s::ap_const_lv4_7 = "111";
const sc_lv<4> dense_array_ap_fixed_4u_array_ap_fixed_28_16_1_0_0_16u_config15_s::ap_const_lv4_8 = "1000";
const sc_lv<4> dense_array_ap_fixed_4u_array_ap_fixed_28_16_1_0_0_16u_config15_s::ap_const_lv4_9 = "1001";
const sc_lv<4> dense_array_ap_fixed_4u_array_ap_fixed_28_16_1_0_0_16u_config15_s::ap_const_lv4_A = "1010";
const sc_lv<4> dense_array_ap_fixed_4u_array_ap_fixed_28_16_1_0_0_16u_config15_s::ap_const_lv4_B = "1011";
const sc_lv<4> dense_array_ap_fixed_4u_array_ap_fixed_28_16_1_0_0_16u_config15_s::ap_const_lv4_C = "1100";
const sc_lv<4> dense_array_ap_fixed_4u_array_ap_fixed_28_16_1_0_0_16u_config15_s::ap_const_lv4_D = "1101";
const sc_lv<4> dense_array_ap_fixed_4u_array_ap_fixed_28_16_1_0_0_16u_config15_s::ap_const_lv4_E = "1110";
const sc_lv<4> dense_array_ap_fixed_4u_array_ap_fixed_28_16_1_0_0_16u_config15_s::ap_const_lv4_F = "1111";
const sc_lv<5> dense_array_ap_fixed_4u_array_ap_fixed_28_16_1_0_0_16u_config15_s::ap_const_lv5_10 = "10000";
const sc_lv<5> dense_array_ap_fixed_4u_array_ap_fixed_28_16_1_0_0_16u_config15_s::ap_const_lv5_1 = "1";

dense_array_ap_fixed_4u_array_ap_fixed_28_16_1_0_0_16u_config15_s::dense_array_ap_fixed_4u_array_ap_fixed_28_16_1_0_0_16u_config15_s(sc_module_name name) : sc_module(name), mVcdFile(0) {
    grp_dense_wrapper_ap_fixed_28_16_1_0_0_ap_fixed_28_16_1_0_0_config15_s_fu_687 = new dense_wrapper_ap_fixed_28_16_1_0_0_ap_fixed_28_16_1_0_0_config15_s("grp_dense_wrapper_ap_fixed_28_16_1_0_0_ap_fixed_28_16_1_0_0_config15_s_fu_687");
    grp_dense_wrapper_ap_fixed_28_16_1_0_0_ap_fixed_28_16_1_0_0_config15_s_fu_687->ap_clk(ap_clk);
    grp_dense_wrapper_ap_fixed_28_16_1_0_0_ap_fixed_28_16_1_0_0_config15_s_fu_687->ap_rst(ap_rst);
    grp_dense_wrapper_ap_fixed_28_16_1_0_0_ap_fixed_28_16_1_0_0_config15_s_fu_687->data_0_V_read(tmp_data_0_V_fu_356);
    grp_dense_wrapper_ap_fixed_28_16_1_0_0_ap_fixed_28_16_1_0_0_config15_s_fu_687->data_1_V_read(tmp_data_1_V_fu_360);
    grp_dense_wrapper_ap_fixed_28_16_1_0_0_ap_fixed_28_16_1_0_0_config15_s_fu_687->data_2_V_read(tmp_data_2_V_fu_364);
    grp_dense_wrapper_ap_fixed_28_16_1_0_0_ap_fixed_28_16_1_0_0_config15_s_fu_687->data_3_V_read(tmp_data_3_V_fu_368);
    grp_dense_wrapper_ap_fixed_28_16_1_0_0_ap_fixed_28_16_1_0_0_config15_s_fu_687->data_4_V_read(tmp_data_0_V_1_fu_372);
    grp_dense_wrapper_ap_fixed_28_16_1_0_0_ap_fixed_28_16_1_0_0_config15_s_fu_687->data_5_V_read(tmp_data_1_V_1_fu_376);
    grp_dense_wrapper_ap_fixed_28_16_1_0_0_ap_fixed_28_16_1_0_0_config15_s_fu_687->data_6_V_read(tmp_data_2_V_1_fu_380);
    grp_dense_wrapper_ap_fixed_28_16_1_0_0_ap_fixed_28_16_1_0_0_config15_s_fu_687->data_7_V_read(tmp_data_3_V_1_fu_384);
    grp_dense_wrapper_ap_fixed_28_16_1_0_0_ap_fixed_28_16_1_0_0_config15_s_fu_687->data_8_V_read(tmp_data_0_V_2_fu_388);
    grp_dense_wrapper_ap_fixed_28_16_1_0_0_ap_fixed_28_16_1_0_0_config15_s_fu_687->data_9_V_read(tmp_data_1_V_2_fu_392);
    grp_dense_wrapper_ap_fixed_28_16_1_0_0_ap_fixed_28_16_1_0_0_config15_s_fu_687->data_10_V_read(tmp_data_2_V_2_fu_396);
    grp_dense_wrapper_ap_fixed_28_16_1_0_0_ap_fixed_28_16_1_0_0_config15_s_fu_687->data_11_V_read(tmp_data_3_V_2_fu_400);
    grp_dense_wrapper_ap_fixed_28_16_1_0_0_ap_fixed_28_16_1_0_0_config15_s_fu_687->data_12_V_read(tmp_data_0_V_3_fu_404);
    grp_dense_wrapper_ap_fixed_28_16_1_0_0_ap_fixed_28_16_1_0_0_config15_s_fu_687->data_13_V_read(tmp_data_1_V_3_fu_408);
    grp_dense_wrapper_ap_fixed_28_16_1_0_0_ap_fixed_28_16_1_0_0_config15_s_fu_687->data_14_V_read(tmp_data_2_V_3_fu_412);
    grp_dense_wrapper_ap_fixed_28_16_1_0_0_ap_fixed_28_16_1_0_0_config15_s_fu_687->data_15_V_read(tmp_data_3_V_3_fu_416);
    grp_dense_wrapper_ap_fixed_28_16_1_0_0_ap_fixed_28_16_1_0_0_config15_s_fu_687->data_16_V_read(tmp_data_0_V_4_fu_420);
    grp_dense_wrapper_ap_fixed_28_16_1_0_0_ap_fixed_28_16_1_0_0_config15_s_fu_687->data_17_V_read(tmp_data_1_V_4_fu_424);
    grp_dense_wrapper_ap_fixed_28_16_1_0_0_ap_fixed_28_16_1_0_0_config15_s_fu_687->data_18_V_read(tmp_data_2_V_4_fu_428);
    grp_dense_wrapper_ap_fixed_28_16_1_0_0_ap_fixed_28_16_1_0_0_config15_s_fu_687->data_19_V_read(tmp_data_3_V_4_fu_432);
    grp_dense_wrapper_ap_fixed_28_16_1_0_0_ap_fixed_28_16_1_0_0_config15_s_fu_687->data_20_V_read(tmp_data_0_V_5_fu_436);
    grp_dense_wrapper_ap_fixed_28_16_1_0_0_ap_fixed_28_16_1_0_0_config15_s_fu_687->data_21_V_read(tmp_data_1_V_5_fu_440);
    grp_dense_wrapper_ap_fixed_28_16_1_0_0_ap_fixed_28_16_1_0_0_config15_s_fu_687->data_22_V_read(tmp_data_2_V_5_fu_444);
    grp_dense_wrapper_ap_fixed_28_16_1_0_0_ap_fixed_28_16_1_0_0_config15_s_fu_687->data_23_V_read(tmp_data_3_V_5_fu_448);
    grp_dense_wrapper_ap_fixed_28_16_1_0_0_ap_fixed_28_16_1_0_0_config15_s_fu_687->data_24_V_read(tmp_data_0_V_6_fu_452);
    grp_dense_wrapper_ap_fixed_28_16_1_0_0_ap_fixed_28_16_1_0_0_config15_s_fu_687->data_25_V_read(tmp_data_1_V_6_fu_456);
    grp_dense_wrapper_ap_fixed_28_16_1_0_0_ap_fixed_28_16_1_0_0_config15_s_fu_687->data_26_V_read(tmp_data_2_V_6_fu_460);
    grp_dense_wrapper_ap_fixed_28_16_1_0_0_ap_fixed_28_16_1_0_0_config15_s_fu_687->data_27_V_read(tmp_data_3_V_6_fu_464);
    grp_dense_wrapper_ap_fixed_28_16_1_0_0_ap_fixed_28_16_1_0_0_config15_s_fu_687->data_28_V_read(tmp_data_0_V_7_fu_468);
    grp_dense_wrapper_ap_fixed_28_16_1_0_0_ap_fixed_28_16_1_0_0_config15_s_fu_687->data_29_V_read(tmp_data_1_V_7_fu_472);
    grp_dense_wrapper_ap_fixed_28_16_1_0_0_ap_fixed_28_16_1_0_0_config15_s_fu_687->data_30_V_read(tmp_data_2_V_7_fu_476);
    grp_dense_wrapper_ap_fixed_28_16_1_0_0_ap_fixed_28_16_1_0_0_config15_s_fu_687->data_31_V_read(tmp_data_3_V_7_fu_480);
    grp_dense_wrapper_ap_fixed_28_16_1_0_0_ap_fixed_28_16_1_0_0_config15_s_fu_687->data_32_V_read(tmp_data_0_V_8_fu_484);
    grp_dense_wrapper_ap_fixed_28_16_1_0_0_ap_fixed_28_16_1_0_0_config15_s_fu_687->data_33_V_read(tmp_data_1_V_8_fu_488);
    grp_dense_wrapper_ap_fixed_28_16_1_0_0_ap_fixed_28_16_1_0_0_config15_s_fu_687->data_34_V_read(tmp_data_2_V_8_fu_492);
    grp_dense_wrapper_ap_fixed_28_16_1_0_0_ap_fixed_28_16_1_0_0_config15_s_fu_687->data_35_V_read(tmp_data_3_V_8_fu_496);
    grp_dense_wrapper_ap_fixed_28_16_1_0_0_ap_fixed_28_16_1_0_0_config15_s_fu_687->data_36_V_read(tmp_data_0_V_9_fu_500);
    grp_dense_wrapper_ap_fixed_28_16_1_0_0_ap_fixed_28_16_1_0_0_config15_s_fu_687->data_37_V_read(tmp_data_1_V_9_fu_504);
    grp_dense_wrapper_ap_fixed_28_16_1_0_0_ap_fixed_28_16_1_0_0_config15_s_fu_687->data_38_V_read(tmp_data_2_V_9_fu_508);
    grp_dense_wrapper_ap_fixed_28_16_1_0_0_ap_fixed_28_16_1_0_0_config15_s_fu_687->data_39_V_read(tmp_data_3_V_9_fu_512);
    grp_dense_wrapper_ap_fixed_28_16_1_0_0_ap_fixed_28_16_1_0_0_config15_s_fu_687->data_40_V_read(tmp_data_0_V_10_fu_516);
    grp_dense_wrapper_ap_fixed_28_16_1_0_0_ap_fixed_28_16_1_0_0_config15_s_fu_687->data_41_V_read(tmp_data_1_V_10_fu_520);
    grp_dense_wrapper_ap_fixed_28_16_1_0_0_ap_fixed_28_16_1_0_0_config15_s_fu_687->data_42_V_read(tmp_data_2_V_10_fu_524);
    grp_dense_wrapper_ap_fixed_28_16_1_0_0_ap_fixed_28_16_1_0_0_config15_s_fu_687->data_43_V_read(tmp_data_3_V_10_fu_528);
    grp_dense_wrapper_ap_fixed_28_16_1_0_0_ap_fixed_28_16_1_0_0_config15_s_fu_687->data_44_V_read(tmp_data_0_V_11_fu_532);
    grp_dense_wrapper_ap_fixed_28_16_1_0_0_ap_fixed_28_16_1_0_0_config15_s_fu_687->data_45_V_read(tmp_data_1_V_11_fu_536);
    grp_dense_wrapper_ap_fixed_28_16_1_0_0_ap_fixed_28_16_1_0_0_config15_s_fu_687->data_46_V_read(tmp_data_2_V_11_fu_540);
    grp_dense_wrapper_ap_fixed_28_16_1_0_0_ap_fixed_28_16_1_0_0_config15_s_fu_687->data_47_V_read(tmp_data_3_V_11_fu_544);
    grp_dense_wrapper_ap_fixed_28_16_1_0_0_ap_fixed_28_16_1_0_0_config15_s_fu_687->data_48_V_read(tmp_data_0_V_12_fu_548);
    grp_dense_wrapper_ap_fixed_28_16_1_0_0_ap_fixed_28_16_1_0_0_config15_s_fu_687->data_49_V_read(tmp_data_1_V_12_fu_552);
    grp_dense_wrapper_ap_fixed_28_16_1_0_0_ap_fixed_28_16_1_0_0_config15_s_fu_687->data_50_V_read(tmp_data_2_V_12_fu_556);
    grp_dense_wrapper_ap_fixed_28_16_1_0_0_ap_fixed_28_16_1_0_0_config15_s_fu_687->data_51_V_read(tmp_data_3_V_12_fu_560);
    grp_dense_wrapper_ap_fixed_28_16_1_0_0_ap_fixed_28_16_1_0_0_config15_s_fu_687->data_52_V_read(tmp_data_0_V_13_fu_564);
    grp_dense_wrapper_ap_fixed_28_16_1_0_0_ap_fixed_28_16_1_0_0_config15_s_fu_687->data_53_V_read(tmp_data_1_V_13_fu_568);
    grp_dense_wrapper_ap_fixed_28_16_1_0_0_ap_fixed_28_16_1_0_0_config15_s_fu_687->data_54_V_read(tmp_data_2_V_13_fu_572);
    grp_dense_wrapper_ap_fixed_28_16_1_0_0_ap_fixed_28_16_1_0_0_config15_s_fu_687->data_55_V_read(tmp_data_3_V_13_fu_576);
    grp_dense_wrapper_ap_fixed_28_16_1_0_0_ap_fixed_28_16_1_0_0_config15_s_fu_687->data_56_V_read(tmp_data_0_V_14_fu_580);
    grp_dense_wrapper_ap_fixed_28_16_1_0_0_ap_fixed_28_16_1_0_0_config15_s_fu_687->data_57_V_read(tmp_data_1_V_14_fu_584);
    grp_dense_wrapper_ap_fixed_28_16_1_0_0_ap_fixed_28_16_1_0_0_config15_s_fu_687->data_58_V_read(tmp_data_2_V_14_fu_588);
    grp_dense_wrapper_ap_fixed_28_16_1_0_0_ap_fixed_28_16_1_0_0_config15_s_fu_687->data_59_V_read(tmp_data_3_V_14_fu_592);
    grp_dense_wrapper_ap_fixed_28_16_1_0_0_ap_fixed_28_16_1_0_0_config15_s_fu_687->data_60_V_read(tmp_data_0_V_15_fu_596);
    grp_dense_wrapper_ap_fixed_28_16_1_0_0_ap_fixed_28_16_1_0_0_config15_s_fu_687->data_61_V_read(tmp_data_1_V_15_fu_600);
    grp_dense_wrapper_ap_fixed_28_16_1_0_0_ap_fixed_28_16_1_0_0_config15_s_fu_687->data_62_V_read(tmp_data_2_V_15_fu_604);
    grp_dense_wrapper_ap_fixed_28_16_1_0_0_ap_fixed_28_16_1_0_0_config15_s_fu_687->data_63_V_read(tmp_data_3_V_15_fu_608);
    grp_dense_wrapper_ap_fixed_28_16_1_0_0_ap_fixed_28_16_1_0_0_config15_s_fu_687->ap_return_0(grp_dense_wrapper_ap_fixed_28_16_1_0_0_ap_fixed_28_16_1_0_0_config15_s_fu_687_ap_return_0);
    grp_dense_wrapper_ap_fixed_28_16_1_0_0_ap_fixed_28_16_1_0_0_config15_s_fu_687->ap_return_1(grp_dense_wrapper_ap_fixed_28_16_1_0_0_ap_fixed_28_16_1_0_0_config15_s_fu_687_ap_return_1);
    grp_dense_wrapper_ap_fixed_28_16_1_0_0_ap_fixed_28_16_1_0_0_config15_s_fu_687->ap_return_2(grp_dense_wrapper_ap_fixed_28_16_1_0_0_ap_fixed_28_16_1_0_0_config15_s_fu_687_ap_return_2);
    grp_dense_wrapper_ap_fixed_28_16_1_0_0_ap_fixed_28_16_1_0_0_config15_s_fu_687->ap_return_3(grp_dense_wrapper_ap_fixed_28_16_1_0_0_ap_fixed_28_16_1_0_0_config15_s_fu_687_ap_return_3);
    grp_dense_wrapper_ap_fixed_28_16_1_0_0_ap_fixed_28_16_1_0_0_config15_s_fu_687->ap_return_4(grp_dense_wrapper_ap_fixed_28_16_1_0_0_ap_fixed_28_16_1_0_0_config15_s_fu_687_ap_return_4);
    grp_dense_wrapper_ap_fixed_28_16_1_0_0_ap_fixed_28_16_1_0_0_config15_s_fu_687->ap_return_5(grp_dense_wrapper_ap_fixed_28_16_1_0_0_ap_fixed_28_16_1_0_0_config15_s_fu_687_ap_return_5);
    grp_dense_wrapper_ap_fixed_28_16_1_0_0_ap_fixed_28_16_1_0_0_config15_s_fu_687->ap_return_6(grp_dense_wrapper_ap_fixed_28_16_1_0_0_ap_fixed_28_16_1_0_0_config15_s_fu_687_ap_return_6);
    grp_dense_wrapper_ap_fixed_28_16_1_0_0_ap_fixed_28_16_1_0_0_config15_s_fu_687->ap_return_7(grp_dense_wrapper_ap_fixed_28_16_1_0_0_ap_fixed_28_16_1_0_0_config15_s_fu_687_ap_return_7);
    grp_dense_wrapper_ap_fixed_28_16_1_0_0_ap_fixed_28_16_1_0_0_config15_s_fu_687->ap_return_8(grp_dense_wrapper_ap_fixed_28_16_1_0_0_ap_fixed_28_16_1_0_0_config15_s_fu_687_ap_return_8);
    grp_dense_wrapper_ap_fixed_28_16_1_0_0_ap_fixed_28_16_1_0_0_config15_s_fu_687->ap_return_9(grp_dense_wrapper_ap_fixed_28_16_1_0_0_ap_fixed_28_16_1_0_0_config15_s_fu_687_ap_return_9);
    grp_dense_wrapper_ap_fixed_28_16_1_0_0_ap_fixed_28_16_1_0_0_config15_s_fu_687->ap_return_10(grp_dense_wrapper_ap_fixed_28_16_1_0_0_ap_fixed_28_16_1_0_0_config15_s_fu_687_ap_return_10);
    grp_dense_wrapper_ap_fixed_28_16_1_0_0_ap_fixed_28_16_1_0_0_config15_s_fu_687->ap_return_11(grp_dense_wrapper_ap_fixed_28_16_1_0_0_ap_fixed_28_16_1_0_0_config15_s_fu_687_ap_return_11);
    grp_dense_wrapper_ap_fixed_28_16_1_0_0_ap_fixed_28_16_1_0_0_config15_s_fu_687->ap_return_12(grp_dense_wrapper_ap_fixed_28_16_1_0_0_ap_fixed_28_16_1_0_0_config15_s_fu_687_ap_return_12);
    grp_dense_wrapper_ap_fixed_28_16_1_0_0_ap_fixed_28_16_1_0_0_config15_s_fu_687->ap_return_13(grp_dense_wrapper_ap_fixed_28_16_1_0_0_ap_fixed_28_16_1_0_0_config15_s_fu_687_ap_return_13);
    grp_dense_wrapper_ap_fixed_28_16_1_0_0_ap_fixed_28_16_1_0_0_config15_s_fu_687->ap_return_14(grp_dense_wrapper_ap_fixed_28_16_1_0_0_ap_fixed_28_16_1_0_0_config15_s_fu_687_ap_return_14);
    grp_dense_wrapper_ap_fixed_28_16_1_0_0_ap_fixed_28_16_1_0_0_config15_s_fu_687->ap_return_15(grp_dense_wrapper_ap_fixed_28_16_1_0_0_ap_fixed_28_16_1_0_0_config15_s_fu_687_ap_return_15);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage0);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state16);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state17);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_pp0_stage0);

    SC_METHOD(thread_ap_block_pp0_stage0_11001);
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( io_acc_block_signal_op177 );

    SC_METHOD(thread_ap_block_pp0_stage0_subdone);
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( io_acc_block_signal_op177 );

    SC_METHOD(thread_ap_block_state1);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );

    SC_METHOD(thread_ap_block_state2_pp0_stage0_iter0);

    SC_METHOD(thread_ap_block_state3_pp0_stage0_iter1);
    sensitive << ( io_acc_block_signal_op177 );

    SC_METHOD(thread_ap_condition_pp0_exit_iter0_state2);
    sensitive << ( icmp_ln36_fu_755_p2 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state17 );
    sensitive << ( io_acc_block_signal_op345 );

    SC_METHOD(thread_ap_enable_pp0);
    sensitive << ( ap_idle_pp0 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( real_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_idle_pp0);
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( internal_ap_ready );

    SC_METHOD(thread_data_stream_V_data_0_V_blk_n);
    sensitive << ( data_stream_V_data_0_V_empty_n );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_data_stream_V_data_0_V_read);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_data_stream_V_data_1_V_blk_n);
    sensitive << ( data_stream_V_data_1_V_empty_n );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_data_stream_V_data_1_V_read);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_data_stream_V_data_2_V_blk_n);
    sensitive << ( data_stream_V_data_2_V_empty_n );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_data_stream_V_data_2_V_read);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_data_stream_V_data_3_V_blk_n);
    sensitive << ( data_stream_V_data_3_V_empty_n );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_data_stream_V_data_3_V_read);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_i_in_fu_761_p2);
    sensitive << ( i_in_0_reg_676 );

    SC_METHOD(thread_icmp_ln36_fu_755_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( i_in_0_reg_676 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_internal_ap_ready);
    sensitive << ( ap_CS_fsm_state17 );
    sensitive << ( io_acc_block_signal_op345 );

    SC_METHOD(thread_io_acc_block_signal_op177);
    sensitive << ( data_stream_V_data_0_V_empty_n );
    sensitive << ( data_stream_V_data_1_V_empty_n );
    sensitive << ( data_stream_V_data_2_V_empty_n );
    sensitive << ( data_stream_V_data_3_V_empty_n );

    SC_METHOD(thread_io_acc_block_signal_op345);
    sensitive << ( res_stream_V_data_0_V_full_n );
    sensitive << ( res_stream_V_data_1_V_full_n );
    sensitive << ( res_stream_V_data_2_V_full_n );
    sensitive << ( res_stream_V_data_3_V_full_n );
    sensitive << ( res_stream_V_data_4_V_full_n );
    sensitive << ( res_stream_V_data_5_V_full_n );
    sensitive << ( res_stream_V_data_6_V_full_n );
    sensitive << ( res_stream_V_data_7_V_full_n );
    sensitive << ( res_stream_V_data_8_V_full_n );
    sensitive << ( res_stream_V_data_9_V_full_n );
    sensitive << ( res_stream_V_data_10_V_full_n );
    sensitive << ( res_stream_V_data_11_V_full_n );
    sensitive << ( res_stream_V_data_12_V_full_n );
    sensitive << ( res_stream_V_data_13_V_full_n );
    sensitive << ( res_stream_V_data_14_V_full_n );
    sensitive << ( res_stream_V_data_15_V_full_n );

    SC_METHOD(thread_real_start);
    sensitive << ( ap_start );
    sensitive << ( start_full_n );
    sensitive << ( start_once_reg );

    SC_METHOD(thread_res_stream_V_data_0_V_blk_n);
    sensitive << ( res_stream_V_data_0_V_full_n );
    sensitive << ( ap_CS_fsm_state17 );

    SC_METHOD(thread_res_stream_V_data_0_V_din);
    sensitive << ( ap_CS_fsm_state17 );
    sensitive << ( tmp_data_0_V16_reg_2144 );
    sensitive << ( io_acc_block_signal_op345 );

    SC_METHOD(thread_res_stream_V_data_0_V_write);
    sensitive << ( ap_CS_fsm_state17 );
    sensitive << ( io_acc_block_signal_op345 );

    SC_METHOD(thread_res_stream_V_data_10_V_blk_n);
    sensitive << ( res_stream_V_data_10_V_full_n );
    sensitive << ( ap_CS_fsm_state17 );

    SC_METHOD(thread_res_stream_V_data_10_V_din);
    sensitive << ( ap_CS_fsm_state17 );
    sensitive << ( tmp_data_10_V_reg_2194 );
    sensitive << ( io_acc_block_signal_op345 );

    SC_METHOD(thread_res_stream_V_data_10_V_write);
    sensitive << ( ap_CS_fsm_state17 );
    sensitive << ( io_acc_block_signal_op345 );

    SC_METHOD(thread_res_stream_V_data_11_V_blk_n);
    sensitive << ( res_stream_V_data_11_V_full_n );
    sensitive << ( ap_CS_fsm_state17 );

    SC_METHOD(thread_res_stream_V_data_11_V_din);
    sensitive << ( ap_CS_fsm_state17 );
    sensitive << ( tmp_data_11_V_reg_2199 );
    sensitive << ( io_acc_block_signal_op345 );

    SC_METHOD(thread_res_stream_V_data_11_V_write);
    sensitive << ( ap_CS_fsm_state17 );
    sensitive << ( io_acc_block_signal_op345 );

    SC_METHOD(thread_res_stream_V_data_12_V_blk_n);
    sensitive << ( res_stream_V_data_12_V_full_n );
    sensitive << ( ap_CS_fsm_state17 );

    SC_METHOD(thread_res_stream_V_data_12_V_din);
    sensitive << ( ap_CS_fsm_state17 );
    sensitive << ( tmp_data_12_V_reg_2204 );
    sensitive << ( io_acc_block_signal_op345 );

    SC_METHOD(thread_res_stream_V_data_12_V_write);
    sensitive << ( ap_CS_fsm_state17 );
    sensitive << ( io_acc_block_signal_op345 );

    SC_METHOD(thread_res_stream_V_data_13_V_blk_n);
    sensitive << ( res_stream_V_data_13_V_full_n );
    sensitive << ( ap_CS_fsm_state17 );

    SC_METHOD(thread_res_stream_V_data_13_V_din);
    sensitive << ( ap_CS_fsm_state17 );
    sensitive << ( tmp_data_13_V_reg_2209 );
    sensitive << ( io_acc_block_signal_op345 );

    SC_METHOD(thread_res_stream_V_data_13_V_write);
    sensitive << ( ap_CS_fsm_state17 );
    sensitive << ( io_acc_block_signal_op345 );

    SC_METHOD(thread_res_stream_V_data_14_V_blk_n);
    sensitive << ( res_stream_V_data_14_V_full_n );
    sensitive << ( ap_CS_fsm_state17 );

    SC_METHOD(thread_res_stream_V_data_14_V_din);
    sensitive << ( ap_CS_fsm_state17 );
    sensitive << ( tmp_data_14_V_reg_2214 );
    sensitive << ( io_acc_block_signal_op345 );

    SC_METHOD(thread_res_stream_V_data_14_V_write);
    sensitive << ( ap_CS_fsm_state17 );
    sensitive << ( io_acc_block_signal_op345 );

    SC_METHOD(thread_res_stream_V_data_15_V_blk_n);
    sensitive << ( res_stream_V_data_15_V_full_n );
    sensitive << ( ap_CS_fsm_state17 );

    SC_METHOD(thread_res_stream_V_data_15_V_din);
    sensitive << ( ap_CS_fsm_state17 );
    sensitive << ( tmp_data_15_V_reg_2219 );
    sensitive << ( io_acc_block_signal_op345 );

    SC_METHOD(thread_res_stream_V_data_15_V_write);
    sensitive << ( ap_CS_fsm_state17 );
    sensitive << ( io_acc_block_signal_op345 );

    SC_METHOD(thread_res_stream_V_data_1_V_blk_n);
    sensitive << ( res_stream_V_data_1_V_full_n );
    sensitive << ( ap_CS_fsm_state17 );

    SC_METHOD(thread_res_stream_V_data_1_V_din);
    sensitive << ( ap_CS_fsm_state17 );
    sensitive << ( tmp_data_1_V16_reg_2149 );
    sensitive << ( io_acc_block_signal_op345 );

    SC_METHOD(thread_res_stream_V_data_1_V_write);
    sensitive << ( ap_CS_fsm_state17 );
    sensitive << ( io_acc_block_signal_op345 );

    SC_METHOD(thread_res_stream_V_data_2_V_blk_n);
    sensitive << ( res_stream_V_data_2_V_full_n );
    sensitive << ( ap_CS_fsm_state17 );

    SC_METHOD(thread_res_stream_V_data_2_V_din);
    sensitive << ( ap_CS_fsm_state17 );
    sensitive << ( tmp_data_2_V16_reg_2154 );
    sensitive << ( io_acc_block_signal_op345 );

    SC_METHOD(thread_res_stream_V_data_2_V_write);
    sensitive << ( ap_CS_fsm_state17 );
    sensitive << ( io_acc_block_signal_op345 );

    SC_METHOD(thread_res_stream_V_data_3_V_blk_n);
    sensitive << ( res_stream_V_data_3_V_full_n );
    sensitive << ( ap_CS_fsm_state17 );

    SC_METHOD(thread_res_stream_V_data_3_V_din);
    sensitive << ( ap_CS_fsm_state17 );
    sensitive << ( tmp_data_3_V16_reg_2159 );
    sensitive << ( io_acc_block_signal_op345 );

    SC_METHOD(thread_res_stream_V_data_3_V_write);
    sensitive << ( ap_CS_fsm_state17 );
    sensitive << ( io_acc_block_signal_op345 );

    SC_METHOD(thread_res_stream_V_data_4_V_blk_n);
    sensitive << ( res_stream_V_data_4_V_full_n );
    sensitive << ( ap_CS_fsm_state17 );

    SC_METHOD(thread_res_stream_V_data_4_V_din);
    sensitive << ( ap_CS_fsm_state17 );
    sensitive << ( tmp_data_4_V_reg_2164 );
    sensitive << ( io_acc_block_signal_op345 );

    SC_METHOD(thread_res_stream_V_data_4_V_write);
    sensitive << ( ap_CS_fsm_state17 );
    sensitive << ( io_acc_block_signal_op345 );

    SC_METHOD(thread_res_stream_V_data_5_V_blk_n);
    sensitive << ( res_stream_V_data_5_V_full_n );
    sensitive << ( ap_CS_fsm_state17 );

    SC_METHOD(thread_res_stream_V_data_5_V_din);
    sensitive << ( ap_CS_fsm_state17 );
    sensitive << ( tmp_data_5_V_reg_2169 );
    sensitive << ( io_acc_block_signal_op345 );

    SC_METHOD(thread_res_stream_V_data_5_V_write);
    sensitive << ( ap_CS_fsm_state17 );
    sensitive << ( io_acc_block_signal_op345 );

    SC_METHOD(thread_res_stream_V_data_6_V_blk_n);
    sensitive << ( res_stream_V_data_6_V_full_n );
    sensitive << ( ap_CS_fsm_state17 );

    SC_METHOD(thread_res_stream_V_data_6_V_din);
    sensitive << ( ap_CS_fsm_state17 );
    sensitive << ( tmp_data_6_V_reg_2174 );
    sensitive << ( io_acc_block_signal_op345 );

    SC_METHOD(thread_res_stream_V_data_6_V_write);
    sensitive << ( ap_CS_fsm_state17 );
    sensitive << ( io_acc_block_signal_op345 );

    SC_METHOD(thread_res_stream_V_data_7_V_blk_n);
    sensitive << ( res_stream_V_data_7_V_full_n );
    sensitive << ( ap_CS_fsm_state17 );

    SC_METHOD(thread_res_stream_V_data_7_V_din);
    sensitive << ( ap_CS_fsm_state17 );
    sensitive << ( tmp_data_7_V_reg_2179 );
    sensitive << ( io_acc_block_signal_op345 );

    SC_METHOD(thread_res_stream_V_data_7_V_write);
    sensitive << ( ap_CS_fsm_state17 );
    sensitive << ( io_acc_block_signal_op345 );

    SC_METHOD(thread_res_stream_V_data_8_V_blk_n);
    sensitive << ( res_stream_V_data_8_V_full_n );
    sensitive << ( ap_CS_fsm_state17 );

    SC_METHOD(thread_res_stream_V_data_8_V_din);
    sensitive << ( ap_CS_fsm_state17 );
    sensitive << ( tmp_data_8_V_reg_2184 );
    sensitive << ( io_acc_block_signal_op345 );

    SC_METHOD(thread_res_stream_V_data_8_V_write);
    sensitive << ( ap_CS_fsm_state17 );
    sensitive << ( io_acc_block_signal_op345 );

    SC_METHOD(thread_res_stream_V_data_9_V_blk_n);
    sensitive << ( res_stream_V_data_9_V_full_n );
    sensitive << ( ap_CS_fsm_state17 );

    SC_METHOD(thread_res_stream_V_data_9_V_din);
    sensitive << ( ap_CS_fsm_state17 );
    sensitive << ( tmp_data_9_V_reg_2189 );
    sensitive << ( io_acc_block_signal_op345 );

    SC_METHOD(thread_res_stream_V_data_9_V_write);
    sensitive << ( ap_CS_fsm_state17 );
    sensitive << ( io_acc_block_signal_op345 );

    SC_METHOD(thread_start_out);
    sensitive << ( real_start );

    SC_METHOD(thread_start_write);
    sensitive << ( real_start );
    sensitive << ( start_once_reg );

    SC_METHOD(thread_trunc_ln203_fu_767_p1);
    sensitive << ( i_in_0_reg_676 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state17 );
    sensitive << ( icmp_ln36_fu_755_p2 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_block_pp0_stage0_subdone );
    sensitive << ( io_acc_block_signal_op345 );

    start_once_reg = SC_LOGIC_0;
    ap_done_reg = SC_LOGIC_0;
    ap_CS_fsm = "0000000000000001";
    ap_enable_reg_pp0_iter1 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter0 = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "dense_array_ap_fixed_4u_array_ap_fixed_28_16_1_0_0_16u_config15_s_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, start_full_n, "(port)start_full_n");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_continue, "(port)ap_continue");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, start_out, "(port)start_out");
    sc_trace(mVcdFile, start_write, "(port)start_write");
    sc_trace(mVcdFile, data_stream_V_data_0_V_dout, "(port)data_stream_V_data_0_V_dout");
    sc_trace(mVcdFile, data_stream_V_data_0_V_empty_n, "(port)data_stream_V_data_0_V_empty_n");
    sc_trace(mVcdFile, data_stream_V_data_0_V_read, "(port)data_stream_V_data_0_V_read");
    sc_trace(mVcdFile, data_stream_V_data_1_V_dout, "(port)data_stream_V_data_1_V_dout");
    sc_trace(mVcdFile, data_stream_V_data_1_V_empty_n, "(port)data_stream_V_data_1_V_empty_n");
    sc_trace(mVcdFile, data_stream_V_data_1_V_read, "(port)data_stream_V_data_1_V_read");
    sc_trace(mVcdFile, data_stream_V_data_2_V_dout, "(port)data_stream_V_data_2_V_dout");
    sc_trace(mVcdFile, data_stream_V_data_2_V_empty_n, "(port)data_stream_V_data_2_V_empty_n");
    sc_trace(mVcdFile, data_stream_V_data_2_V_read, "(port)data_stream_V_data_2_V_read");
    sc_trace(mVcdFile, data_stream_V_data_3_V_dout, "(port)data_stream_V_data_3_V_dout");
    sc_trace(mVcdFile, data_stream_V_data_3_V_empty_n, "(port)data_stream_V_data_3_V_empty_n");
    sc_trace(mVcdFile, data_stream_V_data_3_V_read, "(port)data_stream_V_data_3_V_read");
    sc_trace(mVcdFile, res_stream_V_data_0_V_din, "(port)res_stream_V_data_0_V_din");
    sc_trace(mVcdFile, res_stream_V_data_0_V_full_n, "(port)res_stream_V_data_0_V_full_n");
    sc_trace(mVcdFile, res_stream_V_data_0_V_write, "(port)res_stream_V_data_0_V_write");
    sc_trace(mVcdFile, res_stream_V_data_1_V_din, "(port)res_stream_V_data_1_V_din");
    sc_trace(mVcdFile, res_stream_V_data_1_V_full_n, "(port)res_stream_V_data_1_V_full_n");
    sc_trace(mVcdFile, res_stream_V_data_1_V_write, "(port)res_stream_V_data_1_V_write");
    sc_trace(mVcdFile, res_stream_V_data_2_V_din, "(port)res_stream_V_data_2_V_din");
    sc_trace(mVcdFile, res_stream_V_data_2_V_full_n, "(port)res_stream_V_data_2_V_full_n");
    sc_trace(mVcdFile, res_stream_V_data_2_V_write, "(port)res_stream_V_data_2_V_write");
    sc_trace(mVcdFile, res_stream_V_data_3_V_din, "(port)res_stream_V_data_3_V_din");
    sc_trace(mVcdFile, res_stream_V_data_3_V_full_n, "(port)res_stream_V_data_3_V_full_n");
    sc_trace(mVcdFile, res_stream_V_data_3_V_write, "(port)res_stream_V_data_3_V_write");
    sc_trace(mVcdFile, res_stream_V_data_4_V_din, "(port)res_stream_V_data_4_V_din");
    sc_trace(mVcdFile, res_stream_V_data_4_V_full_n, "(port)res_stream_V_data_4_V_full_n");
    sc_trace(mVcdFile, res_stream_V_data_4_V_write, "(port)res_stream_V_data_4_V_write");
    sc_trace(mVcdFile, res_stream_V_data_5_V_din, "(port)res_stream_V_data_5_V_din");
    sc_trace(mVcdFile, res_stream_V_data_5_V_full_n, "(port)res_stream_V_data_5_V_full_n");
    sc_trace(mVcdFile, res_stream_V_data_5_V_write, "(port)res_stream_V_data_5_V_write");
    sc_trace(mVcdFile, res_stream_V_data_6_V_din, "(port)res_stream_V_data_6_V_din");
    sc_trace(mVcdFile, res_stream_V_data_6_V_full_n, "(port)res_stream_V_data_6_V_full_n");
    sc_trace(mVcdFile, res_stream_V_data_6_V_write, "(port)res_stream_V_data_6_V_write");
    sc_trace(mVcdFile, res_stream_V_data_7_V_din, "(port)res_stream_V_data_7_V_din");
    sc_trace(mVcdFile, res_stream_V_data_7_V_full_n, "(port)res_stream_V_data_7_V_full_n");
    sc_trace(mVcdFile, res_stream_V_data_7_V_write, "(port)res_stream_V_data_7_V_write");
    sc_trace(mVcdFile, res_stream_V_data_8_V_din, "(port)res_stream_V_data_8_V_din");
    sc_trace(mVcdFile, res_stream_V_data_8_V_full_n, "(port)res_stream_V_data_8_V_full_n");
    sc_trace(mVcdFile, res_stream_V_data_8_V_write, "(port)res_stream_V_data_8_V_write");
    sc_trace(mVcdFile, res_stream_V_data_9_V_din, "(port)res_stream_V_data_9_V_din");
    sc_trace(mVcdFile, res_stream_V_data_9_V_full_n, "(port)res_stream_V_data_9_V_full_n");
    sc_trace(mVcdFile, res_stream_V_data_9_V_write, "(port)res_stream_V_data_9_V_write");
    sc_trace(mVcdFile, res_stream_V_data_10_V_din, "(port)res_stream_V_data_10_V_din");
    sc_trace(mVcdFile, res_stream_V_data_10_V_full_n, "(port)res_stream_V_data_10_V_full_n");
    sc_trace(mVcdFile, res_stream_V_data_10_V_write, "(port)res_stream_V_data_10_V_write");
    sc_trace(mVcdFile, res_stream_V_data_11_V_din, "(port)res_stream_V_data_11_V_din");
    sc_trace(mVcdFile, res_stream_V_data_11_V_full_n, "(port)res_stream_V_data_11_V_full_n");
    sc_trace(mVcdFile, res_stream_V_data_11_V_write, "(port)res_stream_V_data_11_V_write");
    sc_trace(mVcdFile, res_stream_V_data_12_V_din, "(port)res_stream_V_data_12_V_din");
    sc_trace(mVcdFile, res_stream_V_data_12_V_full_n, "(port)res_stream_V_data_12_V_full_n");
    sc_trace(mVcdFile, res_stream_V_data_12_V_write, "(port)res_stream_V_data_12_V_write");
    sc_trace(mVcdFile, res_stream_V_data_13_V_din, "(port)res_stream_V_data_13_V_din");
    sc_trace(mVcdFile, res_stream_V_data_13_V_full_n, "(port)res_stream_V_data_13_V_full_n");
    sc_trace(mVcdFile, res_stream_V_data_13_V_write, "(port)res_stream_V_data_13_V_write");
    sc_trace(mVcdFile, res_stream_V_data_14_V_din, "(port)res_stream_V_data_14_V_din");
    sc_trace(mVcdFile, res_stream_V_data_14_V_full_n, "(port)res_stream_V_data_14_V_full_n");
    sc_trace(mVcdFile, res_stream_V_data_14_V_write, "(port)res_stream_V_data_14_V_write");
    sc_trace(mVcdFile, res_stream_V_data_15_V_din, "(port)res_stream_V_data_15_V_din");
    sc_trace(mVcdFile, res_stream_V_data_15_V_full_n, "(port)res_stream_V_data_15_V_full_n");
    sc_trace(mVcdFile, res_stream_V_data_15_V_write, "(port)res_stream_V_data_15_V_write");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, real_start, "real_start");
    sc_trace(mVcdFile, start_once_reg, "start_once_reg");
    sc_trace(mVcdFile, ap_done_reg, "ap_done_reg");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, internal_ap_ready, "internal_ap_ready");
    sc_trace(mVcdFile, data_stream_V_data_0_V_blk_n, "data_stream_V_data_0_V_blk_n");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage0, "ap_CS_fsm_pp0_stage0");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter1, "ap_enable_reg_pp0_iter1");
    sc_trace(mVcdFile, ap_block_pp0_stage0, "ap_block_pp0_stage0");
    sc_trace(mVcdFile, data_stream_V_data_1_V_blk_n, "data_stream_V_data_1_V_blk_n");
    sc_trace(mVcdFile, data_stream_V_data_2_V_blk_n, "data_stream_V_data_2_V_blk_n");
    sc_trace(mVcdFile, data_stream_V_data_3_V_blk_n, "data_stream_V_data_3_V_blk_n");
    sc_trace(mVcdFile, res_stream_V_data_0_V_blk_n, "res_stream_V_data_0_V_blk_n");
    sc_trace(mVcdFile, ap_CS_fsm_state17, "ap_CS_fsm_state17");
    sc_trace(mVcdFile, res_stream_V_data_1_V_blk_n, "res_stream_V_data_1_V_blk_n");
    sc_trace(mVcdFile, res_stream_V_data_2_V_blk_n, "res_stream_V_data_2_V_blk_n");
    sc_trace(mVcdFile, res_stream_V_data_3_V_blk_n, "res_stream_V_data_3_V_blk_n");
    sc_trace(mVcdFile, res_stream_V_data_4_V_blk_n, "res_stream_V_data_4_V_blk_n");
    sc_trace(mVcdFile, res_stream_V_data_5_V_blk_n, "res_stream_V_data_5_V_blk_n");
    sc_trace(mVcdFile, res_stream_V_data_6_V_blk_n, "res_stream_V_data_6_V_blk_n");
    sc_trace(mVcdFile, res_stream_V_data_7_V_blk_n, "res_stream_V_data_7_V_blk_n");
    sc_trace(mVcdFile, res_stream_V_data_8_V_blk_n, "res_stream_V_data_8_V_blk_n");
    sc_trace(mVcdFile, res_stream_V_data_9_V_blk_n, "res_stream_V_data_9_V_blk_n");
    sc_trace(mVcdFile, res_stream_V_data_10_V_blk_n, "res_stream_V_data_10_V_blk_n");
    sc_trace(mVcdFile, res_stream_V_data_11_V_blk_n, "res_stream_V_data_11_V_blk_n");
    sc_trace(mVcdFile, res_stream_V_data_12_V_blk_n, "res_stream_V_data_12_V_blk_n");
    sc_trace(mVcdFile, res_stream_V_data_13_V_blk_n, "res_stream_V_data_13_V_blk_n");
    sc_trace(mVcdFile, res_stream_V_data_14_V_blk_n, "res_stream_V_data_14_V_blk_n");
    sc_trace(mVcdFile, res_stream_V_data_15_V_blk_n, "res_stream_V_data_15_V_blk_n");
    sc_trace(mVcdFile, i_in_0_reg_676, "i_in_0_reg_676");
    sc_trace(mVcdFile, icmp_ln36_fu_755_p2, "icmp_ln36_fu_755_p2");
    sc_trace(mVcdFile, ap_block_state2_pp0_stage0_iter0, "ap_block_state2_pp0_stage0_iter0");
    sc_trace(mVcdFile, io_acc_block_signal_op177, "io_acc_block_signal_op177");
    sc_trace(mVcdFile, ap_block_state3_pp0_stage0_iter1, "ap_block_state3_pp0_stage0_iter1");
    sc_trace(mVcdFile, ap_block_pp0_stage0_11001, "ap_block_pp0_stage0_11001");
    sc_trace(mVcdFile, i_in_fu_761_p2, "i_in_fu_761_p2");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter0, "ap_enable_reg_pp0_iter0");
    sc_trace(mVcdFile, trunc_ln203_fu_767_p1, "trunc_ln203_fu_767_p1");
    sc_trace(mVcdFile, trunc_ln203_reg_1820, "trunc_ln203_reg_1820");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, tmp_data_0_V16_reg_2144, "tmp_data_0_V16_reg_2144");
    sc_trace(mVcdFile, ap_CS_fsm_state16, "ap_CS_fsm_state16");
    sc_trace(mVcdFile, tmp_data_1_V16_reg_2149, "tmp_data_1_V16_reg_2149");
    sc_trace(mVcdFile, tmp_data_2_V16_reg_2154, "tmp_data_2_V16_reg_2154");
    sc_trace(mVcdFile, tmp_data_3_V16_reg_2159, "tmp_data_3_V16_reg_2159");
    sc_trace(mVcdFile, tmp_data_4_V_reg_2164, "tmp_data_4_V_reg_2164");
    sc_trace(mVcdFile, tmp_data_5_V_reg_2169, "tmp_data_5_V_reg_2169");
    sc_trace(mVcdFile, tmp_data_6_V_reg_2174, "tmp_data_6_V_reg_2174");
    sc_trace(mVcdFile, tmp_data_7_V_reg_2179, "tmp_data_7_V_reg_2179");
    sc_trace(mVcdFile, tmp_data_8_V_reg_2184, "tmp_data_8_V_reg_2184");
    sc_trace(mVcdFile, tmp_data_9_V_reg_2189, "tmp_data_9_V_reg_2189");
    sc_trace(mVcdFile, tmp_data_10_V_reg_2194, "tmp_data_10_V_reg_2194");
    sc_trace(mVcdFile, tmp_data_11_V_reg_2199, "tmp_data_11_V_reg_2199");
    sc_trace(mVcdFile, tmp_data_12_V_reg_2204, "tmp_data_12_V_reg_2204");
    sc_trace(mVcdFile, tmp_data_13_V_reg_2209, "tmp_data_13_V_reg_2209");
    sc_trace(mVcdFile, tmp_data_14_V_reg_2214, "tmp_data_14_V_reg_2214");
    sc_trace(mVcdFile, tmp_data_15_V_reg_2219, "tmp_data_15_V_reg_2219");
    sc_trace(mVcdFile, ap_block_state1, "ap_block_state1");
    sc_trace(mVcdFile, ap_block_pp0_stage0_subdone, "ap_block_pp0_stage0_subdone");
    sc_trace(mVcdFile, ap_condition_pp0_exit_iter0_state2, "ap_condition_pp0_exit_iter0_state2");
    sc_trace(mVcdFile, grp_dense_wrapper_ap_fixed_28_16_1_0_0_ap_fixed_28_16_1_0_0_config15_s_fu_687_ap_return_0, "grp_dense_wrapper_ap_fixed_28_16_1_0_0_ap_fixed_28_16_1_0_0_config15_s_fu_687_ap_return_0");
    sc_trace(mVcdFile, grp_dense_wrapper_ap_fixed_28_16_1_0_0_ap_fixed_28_16_1_0_0_config15_s_fu_687_ap_return_1, "grp_dense_wrapper_ap_fixed_28_16_1_0_0_ap_fixed_28_16_1_0_0_config15_s_fu_687_ap_return_1");
    sc_trace(mVcdFile, grp_dense_wrapper_ap_fixed_28_16_1_0_0_ap_fixed_28_16_1_0_0_config15_s_fu_687_ap_return_2, "grp_dense_wrapper_ap_fixed_28_16_1_0_0_ap_fixed_28_16_1_0_0_config15_s_fu_687_ap_return_2");
    sc_trace(mVcdFile, grp_dense_wrapper_ap_fixed_28_16_1_0_0_ap_fixed_28_16_1_0_0_config15_s_fu_687_ap_return_3, "grp_dense_wrapper_ap_fixed_28_16_1_0_0_ap_fixed_28_16_1_0_0_config15_s_fu_687_ap_return_3");
    sc_trace(mVcdFile, grp_dense_wrapper_ap_fixed_28_16_1_0_0_ap_fixed_28_16_1_0_0_config15_s_fu_687_ap_return_4, "grp_dense_wrapper_ap_fixed_28_16_1_0_0_ap_fixed_28_16_1_0_0_config15_s_fu_687_ap_return_4");
    sc_trace(mVcdFile, grp_dense_wrapper_ap_fixed_28_16_1_0_0_ap_fixed_28_16_1_0_0_config15_s_fu_687_ap_return_5, "grp_dense_wrapper_ap_fixed_28_16_1_0_0_ap_fixed_28_16_1_0_0_config15_s_fu_687_ap_return_5");
    sc_trace(mVcdFile, grp_dense_wrapper_ap_fixed_28_16_1_0_0_ap_fixed_28_16_1_0_0_config15_s_fu_687_ap_return_6, "grp_dense_wrapper_ap_fixed_28_16_1_0_0_ap_fixed_28_16_1_0_0_config15_s_fu_687_ap_return_6");
    sc_trace(mVcdFile, grp_dense_wrapper_ap_fixed_28_16_1_0_0_ap_fixed_28_16_1_0_0_config15_s_fu_687_ap_return_7, "grp_dense_wrapper_ap_fixed_28_16_1_0_0_ap_fixed_28_16_1_0_0_config15_s_fu_687_ap_return_7");
    sc_trace(mVcdFile, grp_dense_wrapper_ap_fixed_28_16_1_0_0_ap_fixed_28_16_1_0_0_config15_s_fu_687_ap_return_8, "grp_dense_wrapper_ap_fixed_28_16_1_0_0_ap_fixed_28_16_1_0_0_config15_s_fu_687_ap_return_8");
    sc_trace(mVcdFile, grp_dense_wrapper_ap_fixed_28_16_1_0_0_ap_fixed_28_16_1_0_0_config15_s_fu_687_ap_return_9, "grp_dense_wrapper_ap_fixed_28_16_1_0_0_ap_fixed_28_16_1_0_0_config15_s_fu_687_ap_return_9");
    sc_trace(mVcdFile, grp_dense_wrapper_ap_fixed_28_16_1_0_0_ap_fixed_28_16_1_0_0_config15_s_fu_687_ap_return_10, "grp_dense_wrapper_ap_fixed_28_16_1_0_0_ap_fixed_28_16_1_0_0_config15_s_fu_687_ap_return_10");
    sc_trace(mVcdFile, grp_dense_wrapper_ap_fixed_28_16_1_0_0_ap_fixed_28_16_1_0_0_config15_s_fu_687_ap_return_11, "grp_dense_wrapper_ap_fixed_28_16_1_0_0_ap_fixed_28_16_1_0_0_config15_s_fu_687_ap_return_11");
    sc_trace(mVcdFile, grp_dense_wrapper_ap_fixed_28_16_1_0_0_ap_fixed_28_16_1_0_0_config15_s_fu_687_ap_return_12, "grp_dense_wrapper_ap_fixed_28_16_1_0_0_ap_fixed_28_16_1_0_0_config15_s_fu_687_ap_return_12");
    sc_trace(mVcdFile, grp_dense_wrapper_ap_fixed_28_16_1_0_0_ap_fixed_28_16_1_0_0_config15_s_fu_687_ap_return_13, "grp_dense_wrapper_ap_fixed_28_16_1_0_0_ap_fixed_28_16_1_0_0_config15_s_fu_687_ap_return_13");
    sc_trace(mVcdFile, grp_dense_wrapper_ap_fixed_28_16_1_0_0_ap_fixed_28_16_1_0_0_config15_s_fu_687_ap_return_14, "grp_dense_wrapper_ap_fixed_28_16_1_0_0_ap_fixed_28_16_1_0_0_config15_s_fu_687_ap_return_14");
    sc_trace(mVcdFile, grp_dense_wrapper_ap_fixed_28_16_1_0_0_ap_fixed_28_16_1_0_0_config15_s_fu_687_ap_return_15, "grp_dense_wrapper_ap_fixed_28_16_1_0_0_ap_fixed_28_16_1_0_0_config15_s_fu_687_ap_return_15");
    sc_trace(mVcdFile, tmp_data_0_V_fu_356, "tmp_data_0_V_fu_356");
    sc_trace(mVcdFile, tmp_data_1_V_fu_360, "tmp_data_1_V_fu_360");
    sc_trace(mVcdFile, tmp_data_2_V_fu_364, "tmp_data_2_V_fu_364");
    sc_trace(mVcdFile, tmp_data_3_V_fu_368, "tmp_data_3_V_fu_368");
    sc_trace(mVcdFile, tmp_data_0_V_1_fu_372, "tmp_data_0_V_1_fu_372");
    sc_trace(mVcdFile, tmp_data_1_V_1_fu_376, "tmp_data_1_V_1_fu_376");
    sc_trace(mVcdFile, tmp_data_2_V_1_fu_380, "tmp_data_2_V_1_fu_380");
    sc_trace(mVcdFile, tmp_data_3_V_1_fu_384, "tmp_data_3_V_1_fu_384");
    sc_trace(mVcdFile, tmp_data_0_V_2_fu_388, "tmp_data_0_V_2_fu_388");
    sc_trace(mVcdFile, tmp_data_1_V_2_fu_392, "tmp_data_1_V_2_fu_392");
    sc_trace(mVcdFile, tmp_data_2_V_2_fu_396, "tmp_data_2_V_2_fu_396");
    sc_trace(mVcdFile, tmp_data_3_V_2_fu_400, "tmp_data_3_V_2_fu_400");
    sc_trace(mVcdFile, tmp_data_0_V_3_fu_404, "tmp_data_0_V_3_fu_404");
    sc_trace(mVcdFile, tmp_data_1_V_3_fu_408, "tmp_data_1_V_3_fu_408");
    sc_trace(mVcdFile, tmp_data_2_V_3_fu_412, "tmp_data_2_V_3_fu_412");
    sc_trace(mVcdFile, tmp_data_3_V_3_fu_416, "tmp_data_3_V_3_fu_416");
    sc_trace(mVcdFile, tmp_data_0_V_4_fu_420, "tmp_data_0_V_4_fu_420");
    sc_trace(mVcdFile, tmp_data_1_V_4_fu_424, "tmp_data_1_V_4_fu_424");
    sc_trace(mVcdFile, tmp_data_2_V_4_fu_428, "tmp_data_2_V_4_fu_428");
    sc_trace(mVcdFile, tmp_data_3_V_4_fu_432, "tmp_data_3_V_4_fu_432");
    sc_trace(mVcdFile, tmp_data_0_V_5_fu_436, "tmp_data_0_V_5_fu_436");
    sc_trace(mVcdFile, tmp_data_1_V_5_fu_440, "tmp_data_1_V_5_fu_440");
    sc_trace(mVcdFile, tmp_data_2_V_5_fu_444, "tmp_data_2_V_5_fu_444");
    sc_trace(mVcdFile, tmp_data_3_V_5_fu_448, "tmp_data_3_V_5_fu_448");
    sc_trace(mVcdFile, tmp_data_0_V_6_fu_452, "tmp_data_0_V_6_fu_452");
    sc_trace(mVcdFile, tmp_data_1_V_6_fu_456, "tmp_data_1_V_6_fu_456");
    sc_trace(mVcdFile, tmp_data_2_V_6_fu_460, "tmp_data_2_V_6_fu_460");
    sc_trace(mVcdFile, tmp_data_3_V_6_fu_464, "tmp_data_3_V_6_fu_464");
    sc_trace(mVcdFile, tmp_data_0_V_7_fu_468, "tmp_data_0_V_7_fu_468");
    sc_trace(mVcdFile, tmp_data_1_V_7_fu_472, "tmp_data_1_V_7_fu_472");
    sc_trace(mVcdFile, tmp_data_2_V_7_fu_476, "tmp_data_2_V_7_fu_476");
    sc_trace(mVcdFile, tmp_data_3_V_7_fu_480, "tmp_data_3_V_7_fu_480");
    sc_trace(mVcdFile, tmp_data_0_V_8_fu_484, "tmp_data_0_V_8_fu_484");
    sc_trace(mVcdFile, tmp_data_1_V_8_fu_488, "tmp_data_1_V_8_fu_488");
    sc_trace(mVcdFile, tmp_data_2_V_8_fu_492, "tmp_data_2_V_8_fu_492");
    sc_trace(mVcdFile, tmp_data_3_V_8_fu_496, "tmp_data_3_V_8_fu_496");
    sc_trace(mVcdFile, tmp_data_0_V_9_fu_500, "tmp_data_0_V_9_fu_500");
    sc_trace(mVcdFile, tmp_data_1_V_9_fu_504, "tmp_data_1_V_9_fu_504");
    sc_trace(mVcdFile, tmp_data_2_V_9_fu_508, "tmp_data_2_V_9_fu_508");
    sc_trace(mVcdFile, tmp_data_3_V_9_fu_512, "tmp_data_3_V_9_fu_512");
    sc_trace(mVcdFile, tmp_data_0_V_10_fu_516, "tmp_data_0_V_10_fu_516");
    sc_trace(mVcdFile, tmp_data_1_V_10_fu_520, "tmp_data_1_V_10_fu_520");
    sc_trace(mVcdFile, tmp_data_2_V_10_fu_524, "tmp_data_2_V_10_fu_524");
    sc_trace(mVcdFile, tmp_data_3_V_10_fu_528, "tmp_data_3_V_10_fu_528");
    sc_trace(mVcdFile, tmp_data_0_V_11_fu_532, "tmp_data_0_V_11_fu_532");
    sc_trace(mVcdFile, tmp_data_1_V_11_fu_536, "tmp_data_1_V_11_fu_536");
    sc_trace(mVcdFile, tmp_data_2_V_11_fu_540, "tmp_data_2_V_11_fu_540");
    sc_trace(mVcdFile, tmp_data_3_V_11_fu_544, "tmp_data_3_V_11_fu_544");
    sc_trace(mVcdFile, tmp_data_0_V_12_fu_548, "tmp_data_0_V_12_fu_548");
    sc_trace(mVcdFile, tmp_data_1_V_12_fu_552, "tmp_data_1_V_12_fu_552");
    sc_trace(mVcdFile, tmp_data_2_V_12_fu_556, "tmp_data_2_V_12_fu_556");
    sc_trace(mVcdFile, tmp_data_3_V_12_fu_560, "tmp_data_3_V_12_fu_560");
    sc_trace(mVcdFile, tmp_data_0_V_13_fu_564, "tmp_data_0_V_13_fu_564");
    sc_trace(mVcdFile, tmp_data_1_V_13_fu_568, "tmp_data_1_V_13_fu_568");
    sc_trace(mVcdFile, tmp_data_2_V_13_fu_572, "tmp_data_2_V_13_fu_572");
    sc_trace(mVcdFile, tmp_data_3_V_13_fu_576, "tmp_data_3_V_13_fu_576");
    sc_trace(mVcdFile, tmp_data_0_V_14_fu_580, "tmp_data_0_V_14_fu_580");
    sc_trace(mVcdFile, tmp_data_1_V_14_fu_584, "tmp_data_1_V_14_fu_584");
    sc_trace(mVcdFile, tmp_data_2_V_14_fu_588, "tmp_data_2_V_14_fu_588");
    sc_trace(mVcdFile, tmp_data_3_V_14_fu_592, "tmp_data_3_V_14_fu_592");
    sc_trace(mVcdFile, tmp_data_0_V_15_fu_596, "tmp_data_0_V_15_fu_596");
    sc_trace(mVcdFile, tmp_data_1_V_15_fu_600, "tmp_data_1_V_15_fu_600");
    sc_trace(mVcdFile, tmp_data_2_V_15_fu_604, "tmp_data_2_V_15_fu_604");
    sc_trace(mVcdFile, tmp_data_3_V_15_fu_608, "tmp_data_3_V_15_fu_608");
    sc_trace(mVcdFile, io_acc_block_signal_op345, "io_acc_block_signal_op345");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_idle_pp0, "ap_idle_pp0");
    sc_trace(mVcdFile, ap_enable_pp0, "ap_enable_pp0");
#endif

    }
}

dense_array_ap_fixed_4u_array_ap_fixed_28_16_1_0_0_16u_config15_s::~dense_array_ap_fixed_4u_array_ap_fixed_28_16_1_0_0_16u_config15_s() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete grp_dense_wrapper_ap_fixed_28_16_1_0_0_ap_fixed_28_16_1_0_0_config15_s_fu_687;
}

void dense_array_ap_fixed_4u_array_ap_fixed_28_16_1_0_0_16u_config15_s::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_done_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_continue.read())) {
            ap_done_reg = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read()) && 
                    esl_seteq<1,1,1>(io_acc_block_signal_op345.read(), ap_const_logic_1))) {
            ap_done_reg = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter0 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state2.read()))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                    !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter1 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state2.read()))) {
            ap_enable_reg_pp0_iter1 = (ap_condition_pp0_exit_iter0_state2.read() ^ ap_const_logic_1);
        } else if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter1 = ap_enable_reg_pp0_iter0.read();
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                    !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
            ap_enable_reg_pp0_iter1 = ap_const_logic_0;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(icmp_ln36_fu_755_p2.read(), ap_const_lv1_0))) {
        i_in_0_reg_676 = i_in_fu_761_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        i_in_0_reg_676 = ap_const_lv5_0;
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        start_once_reg = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, real_start.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_0, internal_ap_ready.read()))) {
            start_once_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, internal_ap_ready.read())) {
            start_once_reg = ap_const_logic_0;
        }
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read())) {
        tmp_data_0_V16_reg_2144 = grp_dense_wrapper_ap_fixed_28_16_1_0_0_ap_fixed_28_16_1_0_0_config15_s_fu_687_ap_return_0.read();
        tmp_data_10_V_reg_2194 = grp_dense_wrapper_ap_fixed_28_16_1_0_0_ap_fixed_28_16_1_0_0_config15_s_fu_687_ap_return_10.read();
        tmp_data_11_V_reg_2199 = grp_dense_wrapper_ap_fixed_28_16_1_0_0_ap_fixed_28_16_1_0_0_config15_s_fu_687_ap_return_11.read();
        tmp_data_12_V_reg_2204 = grp_dense_wrapper_ap_fixed_28_16_1_0_0_ap_fixed_28_16_1_0_0_config15_s_fu_687_ap_return_12.read();
        tmp_data_13_V_reg_2209 = grp_dense_wrapper_ap_fixed_28_16_1_0_0_ap_fixed_28_16_1_0_0_config15_s_fu_687_ap_return_13.read();
        tmp_data_14_V_reg_2214 = grp_dense_wrapper_ap_fixed_28_16_1_0_0_ap_fixed_28_16_1_0_0_config15_s_fu_687_ap_return_14.read();
        tmp_data_15_V_reg_2219 = grp_dense_wrapper_ap_fixed_28_16_1_0_0_ap_fixed_28_16_1_0_0_config15_s_fu_687_ap_return_15.read();
        tmp_data_1_V16_reg_2149 = grp_dense_wrapper_ap_fixed_28_16_1_0_0_ap_fixed_28_16_1_0_0_config15_s_fu_687_ap_return_1.read();
        tmp_data_2_V16_reg_2154 = grp_dense_wrapper_ap_fixed_28_16_1_0_0_ap_fixed_28_16_1_0_0_config15_s_fu_687_ap_return_2.read();
        tmp_data_3_V16_reg_2159 = grp_dense_wrapper_ap_fixed_28_16_1_0_0_ap_fixed_28_16_1_0_0_config15_s_fu_687_ap_return_3.read();
        tmp_data_4_V_reg_2164 = grp_dense_wrapper_ap_fixed_28_16_1_0_0_ap_fixed_28_16_1_0_0_config15_s_fu_687_ap_return_4.read();
        tmp_data_5_V_reg_2169 = grp_dense_wrapper_ap_fixed_28_16_1_0_0_ap_fixed_28_16_1_0_0_config15_s_fu_687_ap_return_5.read();
        tmp_data_6_V_reg_2174 = grp_dense_wrapper_ap_fixed_28_16_1_0_0_ap_fixed_28_16_1_0_0_config15_s_fu_687_ap_return_6.read();
        tmp_data_7_V_reg_2179 = grp_dense_wrapper_ap_fixed_28_16_1_0_0_ap_fixed_28_16_1_0_0_config15_s_fu_687_ap_return_7.read();
        tmp_data_8_V_reg_2184 = grp_dense_wrapper_ap_fixed_28_16_1_0_0_ap_fixed_28_16_1_0_0_config15_s_fu_687_ap_return_8.read();
        tmp_data_9_V_reg_2189 = grp_dense_wrapper_ap_fixed_28_16_1_0_0_ap_fixed_28_16_1_0_0_config15_s_fu_687_ap_return_9.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,4,4>(trunc_ln203_reg_1820.read(), ap_const_lv4_A))) {
        tmp_data_0_V_10_fu_516 = data_stream_V_data_0_V_dout.read();
        tmp_data_1_V_10_fu_520 = data_stream_V_data_1_V_dout.read();
        tmp_data_2_V_10_fu_524 = data_stream_V_data_2_V_dout.read();
        tmp_data_3_V_10_fu_528 = data_stream_V_data_3_V_dout.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,4,4>(trunc_ln203_reg_1820.read(), ap_const_lv4_B))) {
        tmp_data_0_V_11_fu_532 = data_stream_V_data_0_V_dout.read();
        tmp_data_1_V_11_fu_536 = data_stream_V_data_1_V_dout.read();
        tmp_data_2_V_11_fu_540 = data_stream_V_data_2_V_dout.read();
        tmp_data_3_V_11_fu_544 = data_stream_V_data_3_V_dout.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,4,4>(trunc_ln203_reg_1820.read(), ap_const_lv4_C))) {
        tmp_data_0_V_12_fu_548 = data_stream_V_data_0_V_dout.read();
        tmp_data_1_V_12_fu_552 = data_stream_V_data_1_V_dout.read();
        tmp_data_2_V_12_fu_556 = data_stream_V_data_2_V_dout.read();
        tmp_data_3_V_12_fu_560 = data_stream_V_data_3_V_dout.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,4,4>(trunc_ln203_reg_1820.read(), ap_const_lv4_D))) {
        tmp_data_0_V_13_fu_564 = data_stream_V_data_0_V_dout.read();
        tmp_data_1_V_13_fu_568 = data_stream_V_data_1_V_dout.read();
        tmp_data_2_V_13_fu_572 = data_stream_V_data_2_V_dout.read();
        tmp_data_3_V_13_fu_576 = data_stream_V_data_3_V_dout.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,4,4>(trunc_ln203_reg_1820.read(), ap_const_lv4_E))) {
        tmp_data_0_V_14_fu_580 = data_stream_V_data_0_V_dout.read();
        tmp_data_1_V_14_fu_584 = data_stream_V_data_1_V_dout.read();
        tmp_data_2_V_14_fu_588 = data_stream_V_data_2_V_dout.read();
        tmp_data_3_V_14_fu_592 = data_stream_V_data_3_V_dout.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,4,4>(trunc_ln203_reg_1820.read(), ap_const_lv4_F))) {
        tmp_data_0_V_15_fu_596 = data_stream_V_data_0_V_dout.read();
        tmp_data_1_V_15_fu_600 = data_stream_V_data_1_V_dout.read();
        tmp_data_2_V_15_fu_604 = data_stream_V_data_2_V_dout.read();
        tmp_data_3_V_15_fu_608 = data_stream_V_data_3_V_dout.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,4,4>(trunc_ln203_reg_1820.read(), ap_const_lv4_1))) {
        tmp_data_0_V_1_fu_372 = data_stream_V_data_0_V_dout.read();
        tmp_data_1_V_1_fu_376 = data_stream_V_data_1_V_dout.read();
        tmp_data_2_V_1_fu_380 = data_stream_V_data_2_V_dout.read();
        tmp_data_3_V_1_fu_384 = data_stream_V_data_3_V_dout.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,4,4>(trunc_ln203_reg_1820.read(), ap_const_lv4_2))) {
        tmp_data_0_V_2_fu_388 = data_stream_V_data_0_V_dout.read();
        tmp_data_1_V_2_fu_392 = data_stream_V_data_1_V_dout.read();
        tmp_data_2_V_2_fu_396 = data_stream_V_data_2_V_dout.read();
        tmp_data_3_V_2_fu_400 = data_stream_V_data_3_V_dout.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,4,4>(trunc_ln203_reg_1820.read(), ap_const_lv4_3))) {
        tmp_data_0_V_3_fu_404 = data_stream_V_data_0_V_dout.read();
        tmp_data_1_V_3_fu_408 = data_stream_V_data_1_V_dout.read();
        tmp_data_2_V_3_fu_412 = data_stream_V_data_2_V_dout.read();
        tmp_data_3_V_3_fu_416 = data_stream_V_data_3_V_dout.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,4,4>(trunc_ln203_reg_1820.read(), ap_const_lv4_4))) {
        tmp_data_0_V_4_fu_420 = data_stream_V_data_0_V_dout.read();
        tmp_data_1_V_4_fu_424 = data_stream_V_data_1_V_dout.read();
        tmp_data_2_V_4_fu_428 = data_stream_V_data_2_V_dout.read();
        tmp_data_3_V_4_fu_432 = data_stream_V_data_3_V_dout.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,4,4>(trunc_ln203_reg_1820.read(), ap_const_lv4_5))) {
        tmp_data_0_V_5_fu_436 = data_stream_V_data_0_V_dout.read();
        tmp_data_1_V_5_fu_440 = data_stream_V_data_1_V_dout.read();
        tmp_data_2_V_5_fu_444 = data_stream_V_data_2_V_dout.read();
        tmp_data_3_V_5_fu_448 = data_stream_V_data_3_V_dout.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,4,4>(trunc_ln203_reg_1820.read(), ap_const_lv4_6))) {
        tmp_data_0_V_6_fu_452 = data_stream_V_data_0_V_dout.read();
        tmp_data_1_V_6_fu_456 = data_stream_V_data_1_V_dout.read();
        tmp_data_2_V_6_fu_460 = data_stream_V_data_2_V_dout.read();
        tmp_data_3_V_6_fu_464 = data_stream_V_data_3_V_dout.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,4,4>(trunc_ln203_reg_1820.read(), ap_const_lv4_7))) {
        tmp_data_0_V_7_fu_468 = data_stream_V_data_0_V_dout.read();
        tmp_data_1_V_7_fu_472 = data_stream_V_data_1_V_dout.read();
        tmp_data_2_V_7_fu_476 = data_stream_V_data_2_V_dout.read();
        tmp_data_3_V_7_fu_480 = data_stream_V_data_3_V_dout.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,4,4>(trunc_ln203_reg_1820.read(), ap_const_lv4_8))) {
        tmp_data_0_V_8_fu_484 = data_stream_V_data_0_V_dout.read();
        tmp_data_1_V_8_fu_488 = data_stream_V_data_1_V_dout.read();
        tmp_data_2_V_8_fu_492 = data_stream_V_data_2_V_dout.read();
        tmp_data_3_V_8_fu_496 = data_stream_V_data_3_V_dout.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,4,4>(trunc_ln203_reg_1820.read(), ap_const_lv4_9))) {
        tmp_data_0_V_9_fu_500 = data_stream_V_data_0_V_dout.read();
        tmp_data_1_V_9_fu_504 = data_stream_V_data_1_V_dout.read();
        tmp_data_2_V_9_fu_508 = data_stream_V_data_2_V_dout.read();
        tmp_data_3_V_9_fu_512 = data_stream_V_data_3_V_dout.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,4,4>(trunc_ln203_reg_1820.read(), ap_const_lv4_0))) {
        tmp_data_0_V_fu_356 = data_stream_V_data_0_V_dout.read();
        tmp_data_1_V_fu_360 = data_stream_V_data_1_V_dout.read();
        tmp_data_2_V_fu_364 = data_stream_V_data_2_V_dout.read();
        tmp_data_3_V_fu_368 = data_stream_V_data_3_V_dout.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(icmp_ln36_fu_755_p2.read(), ap_const_lv1_0))) {
        trunc_ln203_reg_1820 = trunc_ln203_fu_767_p1.read();
    }
}

void dense_array_ap_fixed_4u_array_ap_fixed_28_16_1_0_0_16u_config15_s::thread_ap_CS_fsm_pp0_stage0() {
    ap_CS_fsm_pp0_stage0 = ap_CS_fsm.read()[1];
}

void dense_array_ap_fixed_4u_array_ap_fixed_28_16_1_0_0_16u_config15_s::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void dense_array_ap_fixed_4u_array_ap_fixed_28_16_1_0_0_16u_config15_s::thread_ap_CS_fsm_state16() {
    ap_CS_fsm_state16 = ap_CS_fsm.read()[14];
}

void dense_array_ap_fixed_4u_array_ap_fixed_28_16_1_0_0_16u_config15_s::thread_ap_CS_fsm_state17() {
    ap_CS_fsm_state17 = ap_CS_fsm.read()[15];
}

void dense_array_ap_fixed_4u_array_ap_fixed_28_16_1_0_0_16u_config15_s::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[2];
}

void dense_array_ap_fixed_4u_array_ap_fixed_28_16_1_0_0_16u_config15_s::thread_ap_block_pp0_stage0() {
    ap_block_pp0_stage0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dense_array_ap_fixed_4u_array_ap_fixed_28_16_1_0_0_16u_config15_s::thread_ap_block_pp0_stage0_11001() {
    ap_block_pp0_stage0_11001 = (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op177.read()));
}

void dense_array_ap_fixed_4u_array_ap_fixed_28_16_1_0_0_16u_config15_s::thread_ap_block_pp0_stage0_subdone() {
    ap_block_pp0_stage0_subdone = (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op177.read()));
}

void dense_array_ap_fixed_4u_array_ap_fixed_28_16_1_0_0_16u_config15_s::thread_ap_block_state1() {
    ap_block_state1 = (esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1));
}

void dense_array_ap_fixed_4u_array_ap_fixed_28_16_1_0_0_16u_config15_s::thread_ap_block_state2_pp0_stage0_iter0() {
    ap_block_state2_pp0_stage0_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dense_array_ap_fixed_4u_array_ap_fixed_28_16_1_0_0_16u_config15_s::thread_ap_block_state3_pp0_stage0_iter1() {
    ap_block_state3_pp0_stage0_iter1 = esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op177.read());
}

void dense_array_ap_fixed_4u_array_ap_fixed_28_16_1_0_0_16u_config15_s::thread_ap_condition_pp0_exit_iter0_state2() {
    if (esl_seteq<1,1,1>(icmp_ln36_fu_755_p2.read(), ap_const_lv1_1)) {
        ap_condition_pp0_exit_iter0_state2 = ap_const_logic_1;
    } else {
        ap_condition_pp0_exit_iter0_state2 = ap_const_logic_0;
    }
}

void dense_array_ap_fixed_4u_array_ap_fixed_28_16_1_0_0_16u_config15_s::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read()) && 
         esl_seteq<1,1,1>(io_acc_block_signal_op345.read(), ap_const_logic_1))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_done_reg.read();
    }
}

void dense_array_ap_fixed_4u_array_ap_fixed_28_16_1_0_0_16u_config15_s::thread_ap_enable_pp0() {
    ap_enable_pp0 = (ap_idle_pp0.read() ^ ap_const_logic_1);
}

void dense_array_ap_fixed_4u_array_ap_fixed_28_16_1_0_0_16u_config15_s::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void dense_array_ap_fixed_4u_array_ap_fixed_28_16_1_0_0_16u_config15_s::thread_ap_idle_pp0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter1.read()))) {
        ap_idle_pp0 = ap_const_logic_1;
    } else {
        ap_idle_pp0 = ap_const_logic_0;
    }
}

void dense_array_ap_fixed_4u_array_ap_fixed_28_16_1_0_0_16u_config15_s::thread_ap_ready() {
    ap_ready = internal_ap_ready.read();
}

void dense_array_ap_fixed_4u_array_ap_fixed_28_16_1_0_0_16u_config15_s::thread_data_stream_V_data_0_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
        data_stream_V_data_0_V_blk_n = data_stream_V_data_0_V_empty_n.read();
    } else {
        data_stream_V_data_0_V_blk_n = ap_const_logic_1;
    }
}

void dense_array_ap_fixed_4u_array_ap_fixed_28_16_1_0_0_16u_config15_s::thread_data_stream_V_data_0_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        data_stream_V_data_0_V_read = ap_const_logic_1;
    } else {
        data_stream_V_data_0_V_read = ap_const_logic_0;
    }
}

void dense_array_ap_fixed_4u_array_ap_fixed_28_16_1_0_0_16u_config15_s::thread_data_stream_V_data_1_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
        data_stream_V_data_1_V_blk_n = data_stream_V_data_1_V_empty_n.read();
    } else {
        data_stream_V_data_1_V_blk_n = ap_const_logic_1;
    }
}

void dense_array_ap_fixed_4u_array_ap_fixed_28_16_1_0_0_16u_config15_s::thread_data_stream_V_data_1_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        data_stream_V_data_1_V_read = ap_const_logic_1;
    } else {
        data_stream_V_data_1_V_read = ap_const_logic_0;
    }
}

void dense_array_ap_fixed_4u_array_ap_fixed_28_16_1_0_0_16u_config15_s::thread_data_stream_V_data_2_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
        data_stream_V_data_2_V_blk_n = data_stream_V_data_2_V_empty_n.read();
    } else {
        data_stream_V_data_2_V_blk_n = ap_const_logic_1;
    }
}

void dense_array_ap_fixed_4u_array_ap_fixed_28_16_1_0_0_16u_config15_s::thread_data_stream_V_data_2_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        data_stream_V_data_2_V_read = ap_const_logic_1;
    } else {
        data_stream_V_data_2_V_read = ap_const_logic_0;
    }
}

void dense_array_ap_fixed_4u_array_ap_fixed_28_16_1_0_0_16u_config15_s::thread_data_stream_V_data_3_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
        data_stream_V_data_3_V_blk_n = data_stream_V_data_3_V_empty_n.read();
    } else {
        data_stream_V_data_3_V_blk_n = ap_const_logic_1;
    }
}

void dense_array_ap_fixed_4u_array_ap_fixed_28_16_1_0_0_16u_config15_s::thread_data_stream_V_data_3_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        data_stream_V_data_3_V_read = ap_const_logic_1;
    } else {
        data_stream_V_data_3_V_read = ap_const_logic_0;
    }
}

void dense_array_ap_fixed_4u_array_ap_fixed_28_16_1_0_0_16u_config15_s::thread_i_in_fu_761_p2() {
    i_in_fu_761_p2 = (!i_in_0_reg_676.read().is_01() || !ap_const_lv5_1.is_01())? sc_lv<5>(): (sc_biguint<5>(i_in_0_reg_676.read()) + sc_biguint<5>(ap_const_lv5_1));
}

void dense_array_ap_fixed_4u_array_ap_fixed_28_16_1_0_0_16u_config15_s::thread_icmp_ln36_fu_755_p2() {
    icmp_ln36_fu_755_p2 = (!i_in_0_reg_676.read().is_01() || !ap_const_lv5_10.is_01())? sc_lv<1>(): sc_lv<1>(i_in_0_reg_676.read() == ap_const_lv5_10);
}

void dense_array_ap_fixed_4u_array_ap_fixed_28_16_1_0_0_16u_config15_s::thread_internal_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read()) && 
         esl_seteq<1,1,1>(io_acc_block_signal_op345.read(), ap_const_logic_1))) {
        internal_ap_ready = ap_const_logic_1;
    } else {
        internal_ap_ready = ap_const_logic_0;
    }
}

void dense_array_ap_fixed_4u_array_ap_fixed_28_16_1_0_0_16u_config15_s::thread_io_acc_block_signal_op177() {
    io_acc_block_signal_op177 = (data_stream_V_data_0_V_empty_n.read() & data_stream_V_data_1_V_empty_n.read() & data_stream_V_data_2_V_empty_n.read() & data_stream_V_data_3_V_empty_n.read());
}

void dense_array_ap_fixed_4u_array_ap_fixed_28_16_1_0_0_16u_config15_s::thread_io_acc_block_signal_op345() {
    io_acc_block_signal_op345 = (res_stream_V_data_0_V_full_n.read() & res_stream_V_data_1_V_full_n.read() & res_stream_V_data_2_V_full_n.read() & res_stream_V_data_3_V_full_n.read() & res_stream_V_data_4_V_full_n.read() & res_stream_V_data_5_V_full_n.read() & res_stream_V_data_6_V_full_n.read() & res_stream_V_data_7_V_full_n.read() & res_stream_V_data_8_V_full_n.read() & res_stream_V_data_9_V_full_n.read() & res_stream_V_data_10_V_full_n.read() & res_stream_V_data_11_V_full_n.read() & res_stream_V_data_12_V_full_n.read() & res_stream_V_data_13_V_full_n.read() & res_stream_V_data_14_V_full_n.read() & res_stream_V_data_15_V_full_n.read());
}

void dense_array_ap_fixed_4u_array_ap_fixed_28_16_1_0_0_16u_config15_s::thread_real_start() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, start_full_n.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, start_once_reg.read()))) {
        real_start = ap_const_logic_0;
    } else {
        real_start = ap_start.read();
    }
}

void dense_array_ap_fixed_4u_array_ap_fixed_28_16_1_0_0_16u_config15_s::thread_res_stream_V_data_0_V_blk_n() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read())) {
        res_stream_V_data_0_V_blk_n = res_stream_V_data_0_V_full_n.read();
    } else {
        res_stream_V_data_0_V_blk_n = ap_const_logic_1;
    }
}

void dense_array_ap_fixed_4u_array_ap_fixed_28_16_1_0_0_16u_config15_s::thread_res_stream_V_data_0_V_din() {
    res_stream_V_data_0_V_din = tmp_data_0_V16_reg_2144.read();
}

void dense_array_ap_fixed_4u_array_ap_fixed_28_16_1_0_0_16u_config15_s::thread_res_stream_V_data_0_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read()) && 
         esl_seteq<1,1,1>(io_acc_block_signal_op345.read(), ap_const_logic_1))) {
        res_stream_V_data_0_V_write = ap_const_logic_1;
    } else {
        res_stream_V_data_0_V_write = ap_const_logic_0;
    }
}

void dense_array_ap_fixed_4u_array_ap_fixed_28_16_1_0_0_16u_config15_s::thread_res_stream_V_data_10_V_blk_n() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read())) {
        res_stream_V_data_10_V_blk_n = res_stream_V_data_10_V_full_n.read();
    } else {
        res_stream_V_data_10_V_blk_n = ap_const_logic_1;
    }
}

void dense_array_ap_fixed_4u_array_ap_fixed_28_16_1_0_0_16u_config15_s::thread_res_stream_V_data_10_V_din() {
    res_stream_V_data_10_V_din = tmp_data_10_V_reg_2194.read();
}

void dense_array_ap_fixed_4u_array_ap_fixed_28_16_1_0_0_16u_config15_s::thread_res_stream_V_data_10_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read()) && 
         esl_seteq<1,1,1>(io_acc_block_signal_op345.read(), ap_const_logic_1))) {
        res_stream_V_data_10_V_write = ap_const_logic_1;
    } else {
        res_stream_V_data_10_V_write = ap_const_logic_0;
    }
}

void dense_array_ap_fixed_4u_array_ap_fixed_28_16_1_0_0_16u_config15_s::thread_res_stream_V_data_11_V_blk_n() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read())) {
        res_stream_V_data_11_V_blk_n = res_stream_V_data_11_V_full_n.read();
    } else {
        res_stream_V_data_11_V_blk_n = ap_const_logic_1;
    }
}

void dense_array_ap_fixed_4u_array_ap_fixed_28_16_1_0_0_16u_config15_s::thread_res_stream_V_data_11_V_din() {
    res_stream_V_data_11_V_din = tmp_data_11_V_reg_2199.read();
}

void dense_array_ap_fixed_4u_array_ap_fixed_28_16_1_0_0_16u_config15_s::thread_res_stream_V_data_11_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read()) && 
         esl_seteq<1,1,1>(io_acc_block_signal_op345.read(), ap_const_logic_1))) {
        res_stream_V_data_11_V_write = ap_const_logic_1;
    } else {
        res_stream_V_data_11_V_write = ap_const_logic_0;
    }
}

void dense_array_ap_fixed_4u_array_ap_fixed_28_16_1_0_0_16u_config15_s::thread_res_stream_V_data_12_V_blk_n() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read())) {
        res_stream_V_data_12_V_blk_n = res_stream_V_data_12_V_full_n.read();
    } else {
        res_stream_V_data_12_V_blk_n = ap_const_logic_1;
    }
}

void dense_array_ap_fixed_4u_array_ap_fixed_28_16_1_0_0_16u_config15_s::thread_res_stream_V_data_12_V_din() {
    res_stream_V_data_12_V_din = tmp_data_12_V_reg_2204.read();
}

void dense_array_ap_fixed_4u_array_ap_fixed_28_16_1_0_0_16u_config15_s::thread_res_stream_V_data_12_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read()) && 
         esl_seteq<1,1,1>(io_acc_block_signal_op345.read(), ap_const_logic_1))) {
        res_stream_V_data_12_V_write = ap_const_logic_1;
    } else {
        res_stream_V_data_12_V_write = ap_const_logic_0;
    }
}

void dense_array_ap_fixed_4u_array_ap_fixed_28_16_1_0_0_16u_config15_s::thread_res_stream_V_data_13_V_blk_n() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read())) {
        res_stream_V_data_13_V_blk_n = res_stream_V_data_13_V_full_n.read();
    } else {
        res_stream_V_data_13_V_blk_n = ap_const_logic_1;
    }
}

void dense_array_ap_fixed_4u_array_ap_fixed_28_16_1_0_0_16u_config15_s::thread_res_stream_V_data_13_V_din() {
    res_stream_V_data_13_V_din = tmp_data_13_V_reg_2209.read();
}

void dense_array_ap_fixed_4u_array_ap_fixed_28_16_1_0_0_16u_config15_s::thread_res_stream_V_data_13_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read()) && 
         esl_seteq<1,1,1>(io_acc_block_signal_op345.read(), ap_const_logic_1))) {
        res_stream_V_data_13_V_write = ap_const_logic_1;
    } else {
        res_stream_V_data_13_V_write = ap_const_logic_0;
    }
}

void dense_array_ap_fixed_4u_array_ap_fixed_28_16_1_0_0_16u_config15_s::thread_res_stream_V_data_14_V_blk_n() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read())) {
        res_stream_V_data_14_V_blk_n = res_stream_V_data_14_V_full_n.read();
    } else {
        res_stream_V_data_14_V_blk_n = ap_const_logic_1;
    }
}

void dense_array_ap_fixed_4u_array_ap_fixed_28_16_1_0_0_16u_config15_s::thread_res_stream_V_data_14_V_din() {
    res_stream_V_data_14_V_din = tmp_data_14_V_reg_2214.read();
}

void dense_array_ap_fixed_4u_array_ap_fixed_28_16_1_0_0_16u_config15_s::thread_res_stream_V_data_14_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read()) && 
         esl_seteq<1,1,1>(io_acc_block_signal_op345.read(), ap_const_logic_1))) {
        res_stream_V_data_14_V_write = ap_const_logic_1;
    } else {
        res_stream_V_data_14_V_write = ap_const_logic_0;
    }
}

void dense_array_ap_fixed_4u_array_ap_fixed_28_16_1_0_0_16u_config15_s::thread_res_stream_V_data_15_V_blk_n() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read())) {
        res_stream_V_data_15_V_blk_n = res_stream_V_data_15_V_full_n.read();
    } else {
        res_stream_V_data_15_V_blk_n = ap_const_logic_1;
    }
}

void dense_array_ap_fixed_4u_array_ap_fixed_28_16_1_0_0_16u_config15_s::thread_res_stream_V_data_15_V_din() {
    res_stream_V_data_15_V_din = tmp_data_15_V_reg_2219.read();
}

void dense_array_ap_fixed_4u_array_ap_fixed_28_16_1_0_0_16u_config15_s::thread_res_stream_V_data_15_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read()) && 
         esl_seteq<1,1,1>(io_acc_block_signal_op345.read(), ap_const_logic_1))) {
        res_stream_V_data_15_V_write = ap_const_logic_1;
    } else {
        res_stream_V_data_15_V_write = ap_const_logic_0;
    }
}

void dense_array_ap_fixed_4u_array_ap_fixed_28_16_1_0_0_16u_config15_s::thread_res_stream_V_data_1_V_blk_n() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read())) {
        res_stream_V_data_1_V_blk_n = res_stream_V_data_1_V_full_n.read();
    } else {
        res_stream_V_data_1_V_blk_n = ap_const_logic_1;
    }
}

void dense_array_ap_fixed_4u_array_ap_fixed_28_16_1_0_0_16u_config15_s::thread_res_stream_V_data_1_V_din() {
    res_stream_V_data_1_V_din = tmp_data_1_V16_reg_2149.read();
}

void dense_array_ap_fixed_4u_array_ap_fixed_28_16_1_0_0_16u_config15_s::thread_res_stream_V_data_1_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read()) && 
         esl_seteq<1,1,1>(io_acc_block_signal_op345.read(), ap_const_logic_1))) {
        res_stream_V_data_1_V_write = ap_const_logic_1;
    } else {
        res_stream_V_data_1_V_write = ap_const_logic_0;
    }
}

void dense_array_ap_fixed_4u_array_ap_fixed_28_16_1_0_0_16u_config15_s::thread_res_stream_V_data_2_V_blk_n() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read())) {
        res_stream_V_data_2_V_blk_n = res_stream_V_data_2_V_full_n.read();
    } else {
        res_stream_V_data_2_V_blk_n = ap_const_logic_1;
    }
}

void dense_array_ap_fixed_4u_array_ap_fixed_28_16_1_0_0_16u_config15_s::thread_res_stream_V_data_2_V_din() {
    res_stream_V_data_2_V_din = tmp_data_2_V16_reg_2154.read();
}

void dense_array_ap_fixed_4u_array_ap_fixed_28_16_1_0_0_16u_config15_s::thread_res_stream_V_data_2_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read()) && 
         esl_seteq<1,1,1>(io_acc_block_signal_op345.read(), ap_const_logic_1))) {
        res_stream_V_data_2_V_write = ap_const_logic_1;
    } else {
        res_stream_V_data_2_V_write = ap_const_logic_0;
    }
}

void dense_array_ap_fixed_4u_array_ap_fixed_28_16_1_0_0_16u_config15_s::thread_res_stream_V_data_3_V_blk_n() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read())) {
        res_stream_V_data_3_V_blk_n = res_stream_V_data_3_V_full_n.read();
    } else {
        res_stream_V_data_3_V_blk_n = ap_const_logic_1;
    }
}

void dense_array_ap_fixed_4u_array_ap_fixed_28_16_1_0_0_16u_config15_s::thread_res_stream_V_data_3_V_din() {
    res_stream_V_data_3_V_din = tmp_data_3_V16_reg_2159.read();
}

void dense_array_ap_fixed_4u_array_ap_fixed_28_16_1_0_0_16u_config15_s::thread_res_stream_V_data_3_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read()) && 
         esl_seteq<1,1,1>(io_acc_block_signal_op345.read(), ap_const_logic_1))) {
        res_stream_V_data_3_V_write = ap_const_logic_1;
    } else {
        res_stream_V_data_3_V_write = ap_const_logic_0;
    }
}

void dense_array_ap_fixed_4u_array_ap_fixed_28_16_1_0_0_16u_config15_s::thread_res_stream_V_data_4_V_blk_n() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read())) {
        res_stream_V_data_4_V_blk_n = res_stream_V_data_4_V_full_n.read();
    } else {
        res_stream_V_data_4_V_blk_n = ap_const_logic_1;
    }
}

void dense_array_ap_fixed_4u_array_ap_fixed_28_16_1_0_0_16u_config15_s::thread_res_stream_V_data_4_V_din() {
    res_stream_V_data_4_V_din = tmp_data_4_V_reg_2164.read();
}

void dense_array_ap_fixed_4u_array_ap_fixed_28_16_1_0_0_16u_config15_s::thread_res_stream_V_data_4_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read()) && 
         esl_seteq<1,1,1>(io_acc_block_signal_op345.read(), ap_const_logic_1))) {
        res_stream_V_data_4_V_write = ap_const_logic_1;
    } else {
        res_stream_V_data_4_V_write = ap_const_logic_0;
    }
}

void dense_array_ap_fixed_4u_array_ap_fixed_28_16_1_0_0_16u_config15_s::thread_res_stream_V_data_5_V_blk_n() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read())) {
        res_stream_V_data_5_V_blk_n = res_stream_V_data_5_V_full_n.read();
    } else {
        res_stream_V_data_5_V_blk_n = ap_const_logic_1;
    }
}

void dense_array_ap_fixed_4u_array_ap_fixed_28_16_1_0_0_16u_config15_s::thread_res_stream_V_data_5_V_din() {
    res_stream_V_data_5_V_din = tmp_data_5_V_reg_2169.read();
}

void dense_array_ap_fixed_4u_array_ap_fixed_28_16_1_0_0_16u_config15_s::thread_res_stream_V_data_5_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read()) && 
         esl_seteq<1,1,1>(io_acc_block_signal_op345.read(), ap_const_logic_1))) {
        res_stream_V_data_5_V_write = ap_const_logic_1;
    } else {
        res_stream_V_data_5_V_write = ap_const_logic_0;
    }
}

void dense_array_ap_fixed_4u_array_ap_fixed_28_16_1_0_0_16u_config15_s::thread_res_stream_V_data_6_V_blk_n() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read())) {
        res_stream_V_data_6_V_blk_n = res_stream_V_data_6_V_full_n.read();
    } else {
        res_stream_V_data_6_V_blk_n = ap_const_logic_1;
    }
}

void dense_array_ap_fixed_4u_array_ap_fixed_28_16_1_0_0_16u_config15_s::thread_res_stream_V_data_6_V_din() {
    res_stream_V_data_6_V_din = tmp_data_6_V_reg_2174.read();
}

void dense_array_ap_fixed_4u_array_ap_fixed_28_16_1_0_0_16u_config15_s::thread_res_stream_V_data_6_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read()) && 
         esl_seteq<1,1,1>(io_acc_block_signal_op345.read(), ap_const_logic_1))) {
        res_stream_V_data_6_V_write = ap_const_logic_1;
    } else {
        res_stream_V_data_6_V_write = ap_const_logic_0;
    }
}

void dense_array_ap_fixed_4u_array_ap_fixed_28_16_1_0_0_16u_config15_s::thread_res_stream_V_data_7_V_blk_n() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read())) {
        res_stream_V_data_7_V_blk_n = res_stream_V_data_7_V_full_n.read();
    } else {
        res_stream_V_data_7_V_blk_n = ap_const_logic_1;
    }
}

void dense_array_ap_fixed_4u_array_ap_fixed_28_16_1_0_0_16u_config15_s::thread_res_stream_V_data_7_V_din() {
    res_stream_V_data_7_V_din = tmp_data_7_V_reg_2179.read();
}

void dense_array_ap_fixed_4u_array_ap_fixed_28_16_1_0_0_16u_config15_s::thread_res_stream_V_data_7_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read()) && 
         esl_seteq<1,1,1>(io_acc_block_signal_op345.read(), ap_const_logic_1))) {
        res_stream_V_data_7_V_write = ap_const_logic_1;
    } else {
        res_stream_V_data_7_V_write = ap_const_logic_0;
    }
}

void dense_array_ap_fixed_4u_array_ap_fixed_28_16_1_0_0_16u_config15_s::thread_res_stream_V_data_8_V_blk_n() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read())) {
        res_stream_V_data_8_V_blk_n = res_stream_V_data_8_V_full_n.read();
    } else {
        res_stream_V_data_8_V_blk_n = ap_const_logic_1;
    }
}

void dense_array_ap_fixed_4u_array_ap_fixed_28_16_1_0_0_16u_config15_s::thread_res_stream_V_data_8_V_din() {
    res_stream_V_data_8_V_din = tmp_data_8_V_reg_2184.read();
}

void dense_array_ap_fixed_4u_array_ap_fixed_28_16_1_0_0_16u_config15_s::thread_res_stream_V_data_8_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read()) && 
         esl_seteq<1,1,1>(io_acc_block_signal_op345.read(), ap_const_logic_1))) {
        res_stream_V_data_8_V_write = ap_const_logic_1;
    } else {
        res_stream_V_data_8_V_write = ap_const_logic_0;
    }
}

void dense_array_ap_fixed_4u_array_ap_fixed_28_16_1_0_0_16u_config15_s::thread_res_stream_V_data_9_V_blk_n() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read())) {
        res_stream_V_data_9_V_blk_n = res_stream_V_data_9_V_full_n.read();
    } else {
        res_stream_V_data_9_V_blk_n = ap_const_logic_1;
    }
}

void dense_array_ap_fixed_4u_array_ap_fixed_28_16_1_0_0_16u_config15_s::thread_res_stream_V_data_9_V_din() {
    res_stream_V_data_9_V_din = tmp_data_9_V_reg_2189.read();
}

void dense_array_ap_fixed_4u_array_ap_fixed_28_16_1_0_0_16u_config15_s::thread_res_stream_V_data_9_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read()) && 
         esl_seteq<1,1,1>(io_acc_block_signal_op345.read(), ap_const_logic_1))) {
        res_stream_V_data_9_V_write = ap_const_logic_1;
    } else {
        res_stream_V_data_9_V_write = ap_const_logic_0;
    }
}

void dense_array_ap_fixed_4u_array_ap_fixed_28_16_1_0_0_16u_config15_s::thread_start_out() {
    start_out = real_start.read();
}

void dense_array_ap_fixed_4u_array_ap_fixed_28_16_1_0_0_16u_config15_s::thread_start_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, start_once_reg.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, real_start.read()))) {
        start_write = ap_const_logic_1;
    } else {
        start_write = ap_const_logic_0;
    }
}

void dense_array_ap_fixed_4u_array_ap_fixed_28_16_1_0_0_16u_config15_s::thread_trunc_ln203_fu_767_p1() {
    trunc_ln203_fu_767_p1 = i_in_0_reg_676.read().range(4-1, 0);
}

void dense_array_ap_fixed_4u_array_ap_fixed_28_16_1_0_0_16u_config15_s::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if (!(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(icmp_ln36_fu_755_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(icmp_ln36_fu_755_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state4;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            }
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_fsm_state5;
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_fsm_state6;
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_fsm_state7;
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_fsm_state8;
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_fsm_state9;
            break;
        case 128 : 
            ap_NS_fsm = ap_ST_fsm_state10;
            break;
        case 256 : 
            ap_NS_fsm = ap_ST_fsm_state11;
            break;
        case 512 : 
            ap_NS_fsm = ap_ST_fsm_state12;
            break;
        case 1024 : 
            ap_NS_fsm = ap_ST_fsm_state13;
            break;
        case 2048 : 
            ap_NS_fsm = ap_ST_fsm_state14;
            break;
        case 4096 : 
            ap_NS_fsm = ap_ST_fsm_state15;
            break;
        case 8192 : 
            ap_NS_fsm = ap_ST_fsm_state16;
            break;
        case 16384 : 
            ap_NS_fsm = ap_ST_fsm_state17;
            break;
        case 32768 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read()) && esl_seteq<1,1,1>(io_acc_block_signal_op345.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state17;
            }
            break;
        default : 
            ap_NS_fsm = "XXXXXXXXXXXXXXXX";
            break;
    }
}

}

